### ISSUE TITLE
can't use internet from the mobile data (3g or 4g) Hammerhead devel-rc-prop

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-touch#10]
i can't use mobile data to navigate. i can't see the icon of 3g or 4g next to the cellular signal meter. (try to set apn and activate and deactivate plus reboot but not works)

reported by https://launchpad.net/~ilmixmoto

**Comment by Flohack74** [comment]
I have no issues with 4G mobile data on devel channel...

**Comment by ebeton-ro** [comment]
As @Flohack74 said same here. No issues for me.

**Comment by Flohack74** [comment]
@NeoTheThird Is this an old LP bug? I suggest to close it.

**Comment by NeoTheThird** [comment]
Yes, it is. I can't reproduce it either, so i guess we can close this.
