### ISSUE TITLE
Network problem

### ISSUE THREAD

**Issue by laurentGarry** [ubports/ubports-touch#101]
When I click "File Manager" and then "Network" the process goes off and goes to the "Applications" window
Can not access my hard disk drive

**Comment by Flohack74** [comment]
You mean this problem?
![screenshot20170612_093334743](https://user-images.githubusercontent.com/16186470/27023427-cbf2c0b4-4f52-11e7-9645-8bb64238b8da.png)

I will move this bug to here: https://github.com/ubports/filemanager-app since we got separate bugtrackers for Apps and system components.

**Comment by Flohack74** [comment]
Please follow up here: https://github.com/ubports/filemanager-app/issues/1 - I close this bug, since it belongs only to file manager app.
