### ISSUE TITLE
Custom backgrounds

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-touch#104]
It should be possible to set custom backgrounds for unity8-dash.

**Comment by doniks** [comment]
You can: 
Settings -> Background

**Comment by Flohack74** [comment]
Ok maybe @NeoTheThird was not specific enough, we are talking about backgrounds for the dash and the future Today aggregation thingie right?

**Comment by nfsprodriver** [comment]
https://github.com/nfsprodriver/uttweaks This is a working implementation for Custom Wallpapers (DashBackground.qml). It also contains a fix for Scope fonts (ScopeStyle.qml). To install this run the customwallpaper script as root (after chmd +x). Feel free to use and continue this work, if you want to.

**Comment by mateosalta** [comment]
Yes, the dash "apps scope" background.

**Comment by ChloeWolfieGirl** [comment]
We're talking about a background for scopes, not about a background for the upcoming dash, the upcomming sash is a colour which is a bit translucent to show whats underneith, but the scopes are just white.

This bug isnt abut implementing the new unity 8 header image as seen in mockup images.

Please confirm or deny my comment Jan.

**Comment by NeoTheThird** [comment]
@Flohack74 I was talking about scopes (unity8-dash), the current de-facto homescreen of UT. As @nfsprodriver most of the work to add a background there is already done (gj btw). The "future Today aggregation thingie" (official name) will probably evolve from the current scopes view, but that remains to be seen. There are also some people thinking about decoupling unity8-dash from unity 8 itself or [rework it completely](https://www.behance.net/gallery/29848255/Ubuntu-Touch-Vibrant-Venice)... A lot to think about, but for now it wouldn't be too difficult to just allow backgrounds.

As @ChloeWolfieGirl mentioned, latest unity 8 also brings the so-called [app drawer](https://youtu.be/kdpf48f5UKo), that will probably not get a background, it wouldn't really fit.

**Comment by mariogrip** [comment]
This is really simple to implement, I will implement this for ota-2.

**Comment by mariogrip** [comment]
![back](https://user-images.githubusercontent.com/1642635/28758399-6211e5ec-7597-11e7-8880-19ab85f24d56.png)
![dash](https://user-images.githubusercontent.com/1642635/28758398-62112094-7597-11e7-910d-0e7c02e0863c.png)
![store](https://user-images.githubusercontent.com/1642635/28758400-62140ae8-7597-11e7-865e-5cc7e7696240.png)
![today-scope](https://user-images.githubusercontent.com/1642635/28758401-6214eba2-7597-11e7-9595-48196a9ee7d4.png)

**Comment by nfsprodriver** [comment]
How does it look on the Scope selection page? In my custom background version I couldn't get the font white. It's black.

**Comment by mariogrip** [comment]
@nfsprodriver I fixed that part
![scopeslist](https://user-images.githubusercontent.com/1642635/28759317-140b54c8-759c-11e7-8a80-9b7b2062ee99.png)

**Comment by mariogrip** [comment]
here is the code btw:

http://paste.ubuntu.com/25210138/

replace that with this file `/usr/share/unity8/Dash/ScopesListCategoryItem.qml`

**Comment by nfsprodriver** [comment]
Ah, very nice!

**Comment by mariogrip** [comment]
@nfsprodriver I have imported the vivid version of unity8 to https://github.com/ubports/unity8 (branch vivid-dev) right now. Could you send a pull request for the changes you made? so you get proper credit for you amazing work :D

and i'll push the scopes-list and options to enable this on the system settings. 

also while you're at it could you send a pull request for the browser icon :) https://github.com/ubports/webbrowser-app/blob/vivid/webbrowser-app.png

**Comment by nfsprodriver** [comment]
Done

**Comment by mariogrip** [comment]
Fix pushed: https://github.com/ubports/unity8/pull/7 https://github.com/ubports/system-settings/pull/2

**Comment by mardy** [comment]
Note that the text will be unreadable with a white background. I would suggest modifying the `Text` elements of the dash to use:
```
style: Text.Raised
styleColor: "gray"
```
(maybe only if a custom background has been chosen, otherwise this could render the UI uglier, in the other cases)

**Comment by ChloeWolfieGirl** [comment]
A completely white background looks like this
![screenshot20170804_153412116](https://user-images.githubusercontent.com/8162805/28973202-7c4e9eb4-792a-11e7-8eef-1c6a5c21fda2.png)

(this is what the original background looks like before you activate it) http://ryaneller.com/wp-content/uploads/2013/10/plain-white-background.jpg

**Comment by ChloeWolfieGirl** [comment]
Unless you mean when you move to a scope which chooses to have a white background, in which I disagree greatly, making the text grey will make it harder to read the text on the scopes you've changed your background on.

This is a case of, you can't make everyone happy.
If you use scopes which actively chooses to have a white background, (Soundcloud and wattpad are scopes which do this) your options are, turn off background photos, or don't directly use the scopes. for wattpad, you can use the scope books, and that will help you out.

Hopefully someone can take those scopes, and fork them to remove the white background, but changing the text to grey is a bad idea.

If you hold an app icon you get taken to the scope page, the uninstall text is grey, and with some backgrounds, the text is impossible to read.

**Comment by mateosalta** [comment]
with the card background the text chameleons, and may have overrode custom text color, I remember having green text for the commandline app
![screenshot20170828_195133563](https://user-images.githubusercontent.com/1965279/29799616-86814748-8c2a-11e7-82cd-17688006da59.png)
![screenshot20170828_194514623](https://user-images.githubusercontent.com/1965279/29799617-868497c2-8c2a-11e7-9fb9-585c4de36204.png)
