### ISSUE TITLE
N5 not connection to home wifi

### ISSUE THREAD

**Issue by toehold** [ubports/ubports-touch#107]
Hi,

I wanted to tried Nextcloud using N5, but had difficulties seeing the home wifi network.
Only when I connected to the Router and changed the channel from Auto to 10, the N5 could
see the network and connect. Then I set the channel again to auto and it still worked.

Any one an idea or seen this?

**Comment by ebeton-ro** [comment]
One question @toehold what router do you use?

**Comment by NeoTheThird** [comment]
Since we haven't heard back by now and nobody seems to be able to reproduce it, i think we can close this one.
