### ISSUE TITLE
 Oneplus one: Invisible when connected to a PC

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-touch#11]
Bacon, legacy #10.

I have asked this question in the Telegram group and there seem to be others experiencing similar difficulties, but I have yet to see a solution that works. My beloved OPO remains in "stealth" mode, completely invisible to any PC.

Steps to reproduce:
1. Enable developer mode (check)
2. Turn on and unlock OPO, connect it to a linux PC (check)
3. Nothing shows from the PC, no disk mounted, no "adb devices" entry, no "lsusb" entry
4. Try another cable (check)
5. Same as 3.
6. Try another PC (check)
7. Same as 3.
8. Run "adb kill-server" and reboot PC (check)
9. Same as 3.
10. Try solution mentioned in the wiki (https://wiki.ubports.com/wiki/How-to-use-adb-from-ubuntu-desktop) (check)
11. Same as 3.
12. Add file /etc/udev/rules.d/51-android.rules and enter "SUBSYSTEM=="usb", ATTR{idVendor}=="05c6", MODE="0664", GROUP="plugdev"" (check)
13. Reboot PC (check)
14. Same as 3.

This list of things I have tried is very long, but nothing makes any difference. The device is invisible.

Before I bought my OPO, I borrowed a Nexus 5 from a friend and flashed Ubuntu Touch onto it. File system and adb access worked like a breeze. Apparantly the OPO is different, but I never realized it was going to be so difficult to access it.

Update:

When I go into Settings/About/Developer mode and disable "Developer mode", the device suddenly appears in 'lsusb' as:
Bus 002 Device 009: ID 05c6:6764 Qualcomm, Inc. A0001 Phone [OnePlus One]
as expected and I also get a phone icon in the left panel Ubuntu launcher. If I enable "Developer mode" again, it disappears from the list and the phone icon in the left panel disappears.

However, I still cannot mount "bacon" and it doesn't show up in 'adb devices'. Clicking on the phone icon throws an error that it can't mount.

Reported by https://launchpad.net/~tomoqv.

**Comment by tomoqv** [comment]
Could this be the same issue as https://github.com/ubports/ubports-touch/issues/13?

**Comment by tomoqv** [comment]
On 15.04/devel r10 I can finally mount my OPO, but only if I have developer mode set to disabled. When enabling developer mode, the device can't mount again. Seems like the dev mode settings button is inverted.
Regardless of developer mode setting, the device does not expose an adb interface.

**Comment by mariogrip** [comment]
Fix released: https://github.com/ubports/device-files/commit/2d65b596a9e5b9e9b02263c3b4bb0f76a18d25b5 and https://github.com/ubports/build-scripts/commit/9c0f53526ef844d392bbb24f293796a1b5bc9b84
