### ISSUE TITLE
Ghost Update for r30 on E5 legacy/stable

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubports-touch#119]
Suddenly an update r30 is appearing for my E5 which is on legacy. Additionally system-image-cli --list-channels gives  "Exception occurred during channel search, see log file for details."

The update disappears again after restarting system settings. So far did not look into a logfile...

**Comment by UniversalSuperBox** [comment]
Has this happened again @Flohack74? We had a lot of reports of a similar issue when we switched from the Legacy to Stable branch using a redirect, but it only happened once, changed the verison number to `r1`, and was completely benign.

**Comment by Flohack74** [comment]
No it did not appear. But there were also no new updates for E5, so I cant tell if this will happen again or not. My installed version number though is still smth like r27 - I know the thingie has issues with jumping back in version numbers...
