### ISSUE TITLE
Typing bug. More pronounced on Facebook when 'mentioning' a person. Also a backspace issue.

### ISSUE THREAD

**Issue by tenleftfingers** [ubports/ubports-touch#125]
I've noticed two problems when typing. It happens most on Facebook via the browser but I've also seen similar in the standard messaging app and other apps that accept text input.

It's hard to describe, so I'll leave a video at this link for now and try to keep it until the bug is closed.
https://www.dropbox.com/s/mvy8osp95isusrh/ut-typing-bug.mp4?dl=0

1: In FB when I mention someone (blue text appears) and press space, rubbish text is appended (always a part of their name). Sometimes waiting a few seconds before pressing space helps.
2: When I backspace, it takes away too much including the friends name I mentioned. Repeating the process doesn't help either and the problem has no workaround I can find.

This is the single biggest annoyance with Ubuntu Touch at the moment for me. It's not just a Facebook issue, but it's the one I remember and can reproduce the easiest. The backspace problem has happened to me when text messaging too where it became impossible to type certain things.

Aquaris E4.5.
Canonical OTA-15.

**Comment by Flohack74** [comment]
I will transfer this to the keyboard component, we got separate trackers for those things ;)

**Comment by Flohack74** [comment]
This issue was moved to ubports/keyboard-component#10
