### ISSUE TITLE
Unable to add date stamp to photos - Camera App

### ISSUE THREAD

**Issue by UKPhil** [ubports/ubports-touch#130]
Unable to add a time & date stamp to the photos take in both with the camera app and from within the Telegram app.  This is a feature that is needed on a smart phone.

**Comment by Flohack74** [comment]
This issue was moved to ubports/camera-app#2

**Comment by UKPhil** [comment]
@NeoTheThird I do not think this should be marked as "Invalid" as it has been moved to another section and then actioned. If anything this should be set to "Duplicate" as 'Invalid" implies that it is not a real issue. However, as it has been actioned and then implemented, it must of been valid.

**Comment by Flohack74** [comment]
yeah its just closed here and then active in camera app. not invalid ;)
