### ISSUE TITLE
Nexus 4

### ISSUE THREAD

**Issue by fmulcar** [ubports/ubports-touch#138]
The desktop applications,libre office,gimp do not work.

**Comment by UniversalSuperBox** [comment]
Hello @fmulcar,

We're going to need a lot more information than this to consider this a bug in any capacity. 

First, please read https://wiki.ubports.com/wiki/Writing-a-Good-Bug-Report

Also, did you search the forum to see if anyone else was having a similar issue? How about this bug tracker, by looking for "desktop" or "libertine"

After you provide us with more information, we will triage your bug report.
