### ISSUE TITLE
GPS stopped working in Nexus 5, 15.04/rc

### ISSUE THREAD

**Issue by wagafo** [ubports/ubports-touch#139]
GPS seems to have stopped working for me in the Nexus 5 with 15.04/rc. It was working only 4 or 5 days ago exactly with the same  channel and settings, I haven't changed anything AFAICT. I tried "test_gps" from the command line, and it looks OK, at the last line it starts writing "tracking...". There are two lines which show an error though:
phablet@ubuntu-phablet:~$ test_gps
*** setup signal handler
*** get gps interface
*** device info
 id = gps
 name = loc_api GPS Module
 author = Qualcomm USA, Inc.
*** init gps interface
 ** Creating thread: 'Loc_hal_worker' (start=0xb6b427c5, arg=0xf06a70)
 ** After thread_create: 'Loc_hal_worker', error=0 (start=0xb6b427c5, arg=0xf06a70)
 **** Thread wrapper start (start=0xb6b427c5, arg=0xf06a70) ****
open: Unknown error -1226267644
open: Unknown error -1226267644
 Diag_LSM_Init: Failed to open handle to diag driver, error = 2*** setting positioning mode
*** start gps track
*** gps tracking started
*** tracking.... 
*** set capabilities
capability is 00000007
*** tracking.... 
*** tracking.... 
*** tracking.... 
*** tracking.... 

I tried it in the exterior and after 10 minutes it didn'tt catch a signal.  It just repeated "tracking..." from time to time.

If I try to use uNav it throws me a screen telling "GPS is not enabled in your device" or similar.

Another strange thing is that the indicator is always full white. If I try to disable GPS, either with the switch at the indicator, or unmarking it in the settings, after a while it is enabled back by itself.

**Comment by wagafo** [comment]
Now I moved to 15.04/devel and this issue is gone.

**Comment by Flohack74** [comment]
Good to hear! :)
