### ISSUE TITLE
Camera app doesn't work

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-touch#14]
Whenever trying to open the camera app, it asks for permissions (the text is out of the check-box) and when entering camera permissions, it doesn't show up anything saying "Apps that asked for permission" and then a black screen under it

reported by https://launchpad.net/~diogofigueira

logcat: https://bugs.launchpad.net/ubports-opo/+bug/1681949/+attachment/4873843/+files/cameralogcat.log
demesg: https://launchpadlibrarian.net/318906870/cameradmesg.log

**Comment by tomoqv** [comment]
@mariogrip showed a picture taken on bacon in the Telegram chat. When will you add it to the 15.04/devel channel for testing?

**Comment by siucdude** [comment]
Just wondering about the status of this issue? Any progress or testing required?

**Comment by mariogrip** [comment]
Fix released to devel

**Comment by tomoqv** [comment]
That's great news and it works! 
However, there are a few gripes that I have discoverd so far:
1) I get an error when trying to record video
2) Zoom doesn't work
3) Flash doesn't work
4) HDR on seems to put camera in an endless loop

Anyway, thanks for fixing this! It feels like my phone is whole again :-).

**Comment by NeoTheThird** [comment]
@tomoqv Thanks for the feedback. Could you report separate issues for those points if you have time?

**Comment by tomoqv** [comment]
Certainly, as soon as I have time.

**Comment by NeoTheThird** [comment]
Awesome, thank you!

**Comment by mariogrip** [comment]
@tomoqv Got video recording and playback working now, should land in next devel

**Comment by tomoqv** [comment]
@mariogrip Ace!

**Comment by userj** [comment]
This issue returned in:
device: Bacon
channel: 16.04/devel
build: r210

**Comment by dark-eye** [comment]
@userj any chance  that if you still have the issue that you can run 'top' and see if the trust agent is running? ( if it is it might also lead to battery drain )

**Comment by dark-eye** [comment]
@userj any chance  that if you still have the issue that you can run 'top' and see if the trust agent is running? ( if it is it might also lead to battery drain )

**Comment by Jabato01** [comment]
Hi! photos taken with HDR option block the camera app and don't take the photo. My device is Xiaomi MI6 with UBUNTU 16.04 OTA-25. Thanks.
