### ISSUE TITLE
Oneplus one: no 4G option in mobile settings

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-touch#15]
Channel: rc-devel-proposed
Version: r274

I have inserted a cash SIM card, Comviq Amigos (Sweden) in my OPO. It works fine, but I get only 2G and 3G data. The option 2G/3G/4G (faster) is missing in the mobile settings.

**Comment by tomoqv** [comment]
I exchanged my SIM cards between the OPO and Pro5. Pro5 shows 4G option with both cards, OPO no 4G regardless of SIM.

**Comment by mariogrip** [comment]
Fixed https://github.com/ubports/android_device_oneplus_bacon-1/commit/fedd83fe32c31ef5d22eb8e1afebeb11e638ed43

**Comment by tomoqv** [comment]
Thanks! Will this be included in the next OTA or do I need to do anything to make it work?

**Comment by NeoTheThird** [comment]
Marius pushed it two hours ago, so it will land on `legacy` and `rc` in the next [ci](ci.ubports.com) build. You will see an update today or tomorrow.

**Comment by NeoTheThird** [comment]
Does this also fix #12 by any chance @mariogrip?

**Comment by tomoqv** [comment]
I can confirm that 4G now works on my OPO. The other issues mentioned here, https://github.com/ubports/ubports-touch/issues/12 and https://github.com/ubports/ubports-touch/issues/61 still remain though.
