### ISSUE TITLE
Music app does not start 

### ISSUE THREAD

**Issue by ProsOne** [ubports/ubports-touch#151]
When I tap on music app it start 'n close after few seconds

**Comment by TronFourtyTwo** [comment]
Could you provide device name, channel and revision? Also the music-app log would be helpful. Have you tried to reboot?

**Comment by ProsOne** [comment]
Nexus4, build r41(the Channel is the One show on the ubports site)
Yes I have

**Comment by ernesst** [comment]
Already opened : https://github.com/ubports/ubports-touch/issues/58
