### ISSUE TITLE
Can't load video media files

### ISSUE THREAD

**Issue by TronFourtyTwo** [ubports/ubports-touch#152]
device: bacon (One Plus One)
channel: 15.04/devel r50

Steps to reproduce:
With some media file in the Videos folder, open the gallery app. Photos are loaded correctly, videos not: "An error has occurred attempting to load the media".

**Comment by mariogrip** [comment]
Fix released (bacon)

**Comment by Flohack74** [comment]
why remove bacon label? should stay even if the bug is closed to have a good indexing of the history ;)

**Comment by NeoTheThird** [comment]
Normally the label should stay, but in this case it would have been better to create two seperate issues. Since it's the same symptom but different problems, it doesn't make sense to track it together, since the fix is unlikely to be shipped at the same time.

**Comment by NeoTheThird** [comment]
/me didn't scroll up, ignore the last part about separate issues. Fact is: The label should stay.
