### ISSUE TITLE
Unreliable data connection on Pro 5

### ISSUE THREAD

**Issue by the-Mitu** [ubports/ubports-touch#155]
The mobile data connection very often drops randomly. I have an official Meizu Pro 5 Ubuntu Edition from jd.com which came with Ubuntu preinstalled. Some time ago I switched to Ubports builds. I have experienced problems either since I bought the device on both Canonical's and Ubports' images. It is not connected with the signal strength and is not depending on where am I.

- often when I turn the screen on, I have no connction, but after a few seconds it appears. Not every time - sometimes it doesn't appear at all
- it randomle disappears during usage - pretty often
- it does not matter which network (2G, 3G or 4G) I use

Network indicator observations: I'll call the rectangle with "E", "H", "LTE" etc. an Internet symbol that is placed either on the top bar or besides the carrier's name inside the indicator's menu.
- When I see the Internet symbol on both bar and inside the menu, the connection is most probably there, however sometimes it will drop as well
- Sometimes the Internet symbol disappears at all from both menu and bar - the network can be present or not too. Sometimes I experience Internet symbol appearing and disappearing randomly (it will randomly appear and disappear every few seconds)
- When I see network symbol in the menu, but disconnected in the top bar, the network is never there.

I tried to describe somehow my observations, but as you see it's pretty random.

If you need some logs or more information, plese tell in comments what do you need and how can I gather it.

**Comment by Stefano0101** [comment]
On my Pro 5 mobile connection got better after the switch. 
It only happens in area with a low signal, the network manager jumps from Lte to H to E, up and down like crazy, but most of the time is behaving much much better than Canonical image. Another problem rises from this switching is overheating while browsing net as it is constantly strained and the heat is rather high.

**Comment by mihaelmilea** [comment]
I never had an issue woth this on my Pro 5.

**Comment by NeoTheThird** [comment]
@the-Mitu Sorry to see you have so many problems. When switching to the UBports Ubuntu Touch build, what did you use to switch?

Maybe your device is carrying faulty config files. You could try doing a factory reset (Settings > Reset > Erase & Reset All) and see if this and your other issues remain. This will of course result in the loss of the data stored on your device, but it is sometimes better to start from scratch. You can perform a backup of your device with [magic device tool](https://github.com/MariusQuabeck/magic-device-tool/) and restore it in case the issues remain.

**Comment by speedracer08861** [comment]
Never had that problem

**Comment by NeoTheThird** [comment]
Ok, let's close this for now. I would assume it's either a hardware issue or some faulty configurations.

**Comment by the-Mitu** [comment]
A few days ago I have performed the factory reset. The issue still persists (I need more time to tell if its frequency changed).

I found out that after the data connection drops, in most cases entering the flight mode and exiting it makes the data connection go back again.
