### ISSUE TITLE
adb shell uses root user

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-touch#16]
The current image uses adbd as root (and therefore also presents a root shell). This has some consequences:

- No click packages can be automatically deployed to the phone from scripts (Openstore via mdt)
- Automated backup not possible (needs ssh keys & phablet user shell)
- unknown security issues?

Please put exec su -l phablet -c adbd into the file android-tools-adb.conf for all images (not only N5)...

reported by https://launchpad.net/~flori-bin

**Comment by mariogrip** [comment]
Fix released: https://github.com/ubports/device-files/commit/2d65b596a9e5b9e9b02263c3b4bb0f76a18d25b5

**Comment by Flohack74** [comment]
Confirmed on hammerhead, thx!
