### ISSUE TITLE
Flashing UBports image on Meizu Pro 5

### ISSUE THREAD

**Issue by mihaelmilea** [ubports/ubports-touch#161]
I changed to UBports image using [ubports-installer](https://github.com/ubports/ubports-installer) and inspite of all warnings that the device will be reset to factory form and all my data lost, nothing was lost! Yes, when I boot the device I can see the little robot - the UBports logo and the Device image part is 20170608-43243. But since nothing was erased I wonder if I have succesfully switched to UBports image or I still have the old Canonical image. Thank you for your answer and thank you for everything you guys are doing!!! This is amazing!!!

**Comment by Scym1** [comment]
I'm waiting to have a way to update without losing my data on my nexus 5. I'm now tempted to try it...

To look which version you are running you can go in: Settings --> About and look for OS. It should be Ubuntu 15.04 (r1) if it updated correctly. If still in the old channel, it will be (r340).

Tell me if it worked please. I might try it too.

**Comment by mihaelmilea** [comment]
In settings it shows Ubuntu 15.04 (r2) - I guess because I used the rc channel.

Running system-image-cli -i shows:
current build number: 2
device name: turbo
channel: ubports-touch/15.04/rc
last update: 2017-07-12 23:53:28
version version: 2
version ubports: 20170610-30270
version keyring: archive-master
version device: 20170608-43243

I had a complete backup of the /home directory but it was not needed at all.

**Comment by mihaelmilea** [comment]
I would dare to say that without the --wipe option, the ubuntu-device-flash tool will not erase the home partition and thus the switch to ubports image doesn't loose any data... And most probably the ubports-installer uses ubuntu-device-flash without the --wipe option.

**Comment by NeoTheThird** [comment]
If you used the ubports-installer, you should be fine. :)
