### ISSUE TITLE
Please help!

### ISSUE THREAD

**Issue by zhenyolka** [ubports/ubports-touch#162]
Sorry for my English.
How port this to lg l65(snapgragon chipset)? I have ported cyanogen 11 - 14.
What need(utils, disk space, system for build...). And please write me tutorial.

**Comment by Scym1** [comment]
Do you mean that you want to install it? If so, I believe the LG L65 is not a supported device. You can see the list of supported devices here: https://ubports.com/page/fs-flash-phone

Still, with the recent work on Halium, there will be a lot more phones supported in the future. 

If you really mean to port it, I think you can take a look at the Wiki here: https://wiki.ubports.com/wiki/UBports-Development-Information

Also, I think you have better chances to get your questions answered if you post on the Porting forums here : https://forums.ubports.com/category/33/porting

I wish you luck.

**Comment by NeoTheThird** [comment]
The links @Scym1 provided will be useful to you, but if you start porting to a new device now, you might want to port [Halium](halium.org) instead. You can find the information about that here: https://docs.halium.org/en/latest/
