### ISSUE TITLE
No access to the file system while bluetooth connection is active

### ISSUE THREAD

**Issue by bastos77** [ubports/ubports-touch#163]
15.04 (r1) on the FP2:
When bluetooth is active and a bluetooth device is connected I am not able to mount the file system of the device via ubuntu 16.04 file manager.
After restart of the device and de-activating bluetooth mounting was possible again

**Comment by bastos77** [comment]
This is obsolete. Has been a cable issue, so this bug can be closed imo

**Comment by Flohack74** [comment]
Ok feel free to make a new one if needed.
