### ISSUE TITLE
Screen turns black on call

### ISSUE THREAD

**Issue by vigotron** [ubports/ubports-touch#165]
**Story**:
When making and receiving phone calls, once connection is established screen turns off. Seems like proximity sensor is not working properly. Covering and uncovering proximity sensor have no effect on 
screen.

**Environment**:
-# system-image-cli -i
current build number: 7
device name: FP2
channel: ubports-touch/15.04/devel
last update: 1970-04-13 12:39:17
version version: 7
version ubports: 20170531-13919
version keyring: archive-master
version device: 20170531-21104

**Steps to reproduce:**

1. Make a phone call from FP2 or receive one
2. Watch phone's screen when phone call is established (call is picked up)

**Current result:** picking up the phone call turns screen off automatically, in addition when the call is finished screen doesn't wake up until user uses power button

**Expected result:** screen shouldn't turn off when on call. Screen should turn off if proximity sensor is covered and screen should turn on when proximity sensor isn't covered. When phone call is over, proximity sensor is disabled and screen should wake up.

**Add info:** logs attached time stamp 12:15 & 12:23 am 16/07
[logs.zip](https://github.com/ubports/ubports-touch/files/1150720/logs.zip)

**Comment by bastos77** [comment]
Could be that the proximity sensor is not calibrated appropriately.
Lucky me I realized the calibration app already in FP OSOS

**Comment by NeoTheThird** [comment]
I used the configuration tool in FP OSOS as @bastos77 pointed out, and I don't have that issue. Maybe we could create our own calibration tool? I think there are also proximity-sensor related problems in other devices iirc...
