### ISSUE TITLE
browser app not recognized as mobile device

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-touch#17]
Ubports Legacy
r13

What happens:
Websites display in desktop mode. Device not recognized as mobile in the browser.

Expected:
Mobile version of websites displayed.

reported by https://launchpad.net/~joe.

**Comment by tomoqv** [comment]
Still an issue on legacy r15.

**Comment by Flohack74** [comment]
This is also partly a problem how the webbrowser component announces itself with the User Agent string. See here how Canonical tried to fix it: https://github.com/ubports/webbrowser-component/blob/dddcb8eadfd6d49d37aecb3add75940ced3a3ea6/src/Ubuntu/Web/ua-overrides-mobile.js.in - but the solution cannot be to try to add all sites to an exception list.

**Comment by tomoqv** [comment]
Yes, but as I have three UT devices (Turbo, Frieza and Bacon), I can see that the OPO is the only one acting differently displaying many sites, including google searches in desktop mode while the other two displays it as expected on a mobile device. I have to add though, that my OPO is the only of the 3 running UBports.

**Comment by Flohack74** [comment]
Thats because all webservers look on the UA string: Its either iOS or Android, everything else gets desktop. So, should we disguise ourselves always? Its against the spec, but would fix it immediately

**Comment by tomoqv** [comment]
I see what you mean. This used to be a problem a few years back with Canonical's official devices, but has since worked mostly fine. That's why I was surprised to see this problem surface on the OPO with the same browser. This means that I can't use e.g. the GMail webapp and some sites that work fine on the Pro5 are just unreadable on the OPO.

I guess the problem is also on the publisher side, where lazy web devs seem to just look to see if it is an iOS or Android device accessing the website and otherwise throws the full desktop version.

**Comment by Flohack74** [comment]
We also have the problem that we cant continue to use this browser, as it is tightly coupled with system parts we dont want to carry on. A solution is needed here on the long run...

**Comment by NeoTheThird** [comment]
As soon as the future of Oxide is decided, we should create a new issue that's a little more descriptive...

**Comment by ernesst** [comment]
On the mako, while browsing all the page are displayed as deskop. I think it's the same issue isn't ?

**Comment by Flohack74** [comment]
There is no difference between devices. But I must say it cannot be all pages. Try Github, it will show the mobile version for example...

**Comment by tomoqv** [comment]
@Flohack74 Github shows as desktop version on my OPO, see attached pic.
![screenshot20170530_091647802](https://cloud.githubusercontent.com/assets/13762919/26572204/69c923c6-4519-11e7-8138-9269cf133069.png)

**Comment by ernesst** [comment]
in my case for the nexus 4:

![photo5868750571928922381](https://cloud.githubusercontent.com/assets/11337464/26585457/c461daec-4511-11e7-9ea9-7d466f92518f.jpg)
![photo5868750571928922380](https://cloud.githubusercontent.com/assets/11337464/26585455/c44daf7c-4511-11e7-9076-c2a6d8ed56b2.jpg)
![photo5868750571928922379](https://cloud.githubusercontent.com/assets/11337464/26585456/c44f13e4-4511-11e7-81e1-c47a221e3b60.jpg)

**Comment by Flohack74** [comment]
This is VERY weird!!!! :) No idea TBH where this can come from...

**Comment by NeoTheThird** [comment]
Hummm, noticing the same behavior on my FP2 now, interestingly not on my other devices....

**Comment by ernesst** [comment]
Rather an enhancement shouldn't be a bug ?

**Comment by Flohack74** [comment]
Can you please go to http://www.whoishostingthis.com/tools/user-agent/ and post the result (as screenshot please) Thx!

**Comment by tomoqv** [comment]
![screenshot20170601_132046623](https://cloud.githubusercontent.com/assets/13762919/26677689/51ec6a32-46cd-11e7-833c-600026ab10da.png)

**Comment by Flohack74** [comment]
![screenshot20170601_132144788](https://cloud.githubusercontent.com/assets/16186470/26677751/802fcc2c-46cd-11e7-9cee-648312116689.png)

This is mine. OK I accept this as a bug, we need to use the same UA on all devices :)

**Comment by ernesst** [comment]
And mako please

**Comment by Flohack74** [comment]
Note to myself: FIX THIS MESS!!! here: http://bazaar.launchpad.net/~phablet-team/webbrowser-app/staging/view/head:/src/Ubuntu/Web/UserAgent02.qml#L64

**Comment by tomoqv** [comment]
@Flohack74 😀👍

**Comment by salarelv** [comment]
Works fine on my device with the latest devel

**Comment by Flohack74** [comment]
BTW @ernesst its a bug because the method to determine the UA string is questionable if not wrong. It fails because it cant read the device´s diagonal size, and then it reverts to Desktop. Thats to me a bug.

**Comment by Flohack74** [comment]
Can you please check on your devices the output of the following shell commands:
env | grep GRID_UNIT_PX
env | grep QTWEBKIT_DPR
env | grep FORM_FACTOR

Thx!

**Comment by NeoTheThird** [comment]
Here's a paste from cooler: http://paste.ubuntu.com/24751877/

**Comment by ernesst** [comment]
From an hammerheard : https://pastebin.ubuntu.com/24767705/
From an mako : https://pastebin.ubuntu.com/24767693/

**Comment by mariogrip** [comment]
Fix released: https://github.com/ubports/android_hardware_qcom_display/commit/8b2bd9f565288e68ba678ca2fbe7ae74d1dd053a

**Comment by Flohack74** [comment]
@tomoqv Can you follow up this issue with the devel builds and confirm that it works for you?

**Comment by tomoqv** [comment]
Yes, it works on all the pages I have tested. Also in the GMail web app.

**Comment by Flohack74** [comment]
Thats amazing news!

**Comment by ernesst** [comment]
On the mako 15.04/devel rev 23 , i've the mobile view for gmail and duckduckgo, however as soon i come back on google.com it switch to desktop view. 
any idea ?

**Comment by klotzor** [comment]
Can somebody please elaborate how to apply the fix to Ubuntu Touch on Fairphone 2?
