### ISSUE TITLE
Take ownership of the indicators

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-touch#170]
The [indicators] are not forked into GitHub and built on our infrastructure yet. This will make fixing issues like #68 and #108 easier.

- [x] indicator-session
- [x] indicator-power
- [x] indicator-bluetooth
- [x] indicator-datetime
- [x] indicator-sound
- [x] indicator-network
- [x] indicator-location
- [x] indicator-transfer
- [x] indicator-keyboard
- [x] indicator-display
- [x] indicator-messages

**Comment by Flohack74** [comment]
How many of them we have? I have a script to auto-convert from LP to GH.

**Comment by mariogrip** [comment]
@Flohack74 made this https://github.com/mariogrip/bzr-to-git it also edit the debian files so it can get build by jenkins, it also bumps the version. and add the Jenkinsfile so it can get built automatically

**Comment by NeoTheThird** [comment]
@Flohack74 I added a check list, see the first comment. But maybe @mariogrip should handle this, he already set up CI for the first two.

**Comment by NeoTheThird** [comment]
Done :)
https://github.com/search?q=topic%3Aindicator+org%3Aubports+fork%3Atrue
