### ISSUE TITLE
Update system-indicator links

### ISSUE THREAD

**Issue by ChloeWolfieGirl** [ubports/ubports-touch#175]
In the farest right indicator, theres an “Ubuntu Help...” button, if you tap that it takes you to askubuntu.com
Considering ubuntu phone isnt being supported by canonical, this should either be removed, or changed to a ubports page, this could be ubports faq, or the ubports forum, or some other suggestion?

**Comment by doniks** [comment]
To me https://github.com/ubports/ubports-touch/issues/108 and https://github.com/ubports/ubports-touch/issues/175 sound very related. What about: Replace the "Ubuntu help ..." button with "Ubports help ..." and make it launch the app?

**Comment by NeoTheThird** [comment]
askubuntu.com is still open for ubuntu touch questions, but it would make more sense to link to the ubports forum now. @doniks The bugs are very similar, but in my opinion it does make sense to have both a button to open the ubports app and one to open the forums. A link to report bugs couldn't hurt as well.

**Comment by doniks** [comment]
neo, it would make sense. Or maybe better:
 * ubports.com website
 * bug tracker
And then maybe the app itself doesnt need to be linked... I'd say either website or app

**Comment by mariogrip** [comment]
This fixes this https://github.com/ubports/indicator-session/commit/181a24a54466fce42857a22f00a7660199ec8efe

what this does is rename it to UBports help and it now links to the forum.

**Comment by NeoTheThird** [comment]
I have no idea if it works, but this https://github.com/ubports/indicator-session/pull/1 should add a link to the bug tracker.
