### ISSUE TITLE
Hammerhead - Devel - regression in performances

### ISSUE THREAD

**Issue by ernesst** [ubports/ubports-touch#177]
Gents, 

For the lasts images, let says the one from this week, i've noticed a significatif regression in browser performance and unity 8 both got slow and even freeze. 

I come back tonight under the version 54, the phone is more responsive.

**Comment by NeoTheThird** [comment]
I can confirm this.

**Comment by Flohack74** [comment]
The browser has high CPU usage:

![grafik](https://user-images.githubusercontent.com/16186470/28534490-2d3a50ca-70a1-11e7-94e2-0d78b0ed5c16.png)

**Comment by Flohack74** [comment]
I am pretty sure it is only the browser. Can we rename this issue accordingly?

**Comment by ernesst** [comment]
And the main scope page got stuck time to time.

**Comment by NeoTheThird** [comment]
I don't think it's only the browser

**Comment by Flohack74** [comment]
I see slight improvements with today´s devel image

**Comment by ernesst** [comment]
It would be interesting for us, pull log file for instance, to have some change log between rev.

**Comment by Flohack74** [comment]
@ernesst can you test latest devel if it still occurs for you?

**Comment by ernesst** [comment]
Do you have any hint that the regression has been corrected ?

**Comment by Flohack74** [comment]
yes as I can see on my N5 its fluent again, at least better thsn before. NOt sure it is 100% gone so we need testers =)

**Comment by ernesst** [comment]
Ok, i'll try. I was back on RC. 
How did you get the info ? ^^

**Comment by Flohack74** [comment]
I updated to latest devel on my N5 and tried a bit ^

**Comment by mariogrip** [comment]
I cannot reproduce this on the latest devel? is this still an issue?

**Comment by ernesst** [comment]
I've upgraded to the last devel, give me 24h to test

**Comment by ernesst** [comment]
Yes it's better than when i create the ticket. However i've the feeling that it's slightly lower to browse newspaper website than with rc. 

I just got a black screen when launching the browser : Launched a link in landscape mode, when i rotate the phone the layout stay landscape after 20s black screen, unity didn't restarted by itself.

**Comment by ernesst** [comment]
Definitively,  browsing forum like reddit with autoloaded pictures, is faster on Rc. 
Moreover when i come back to the app list, sometime it take 5-10 sec to display all apps.

**Comment by Flohack74** [comment]
Ok with Reddit I can still see it. I will make a video comparison side2side with E5. The N5 should be faster or at least on par of E5, which it isnt.

**Comment by ernesst** [comment]
I've found that the memory is saturated, 
a top gives : 
KiB Mem:   1896596 total,  1853848 used,    42748 free,     2424 buffers
KiB Swap:    32764 total,    32764 used,        0 free.   374732 cached Me

a https://github.com/pixelb/ps_mem gives : 
68.0 KiB +   9.5 KiB =  77.5 KiB	cat
  4.0 KiB +  80.0 KiB =  84.0 KiB	history-daemon
  8.0 KiB +  81.0 KiB =  89.0 KiB	tonegend
 76.0 KiB +  23.5 KiB =  99.5 KiB	upstart-event-bridge
 92.0 KiB +   9.0 KiB = 101.0 KiB	hciattach
  4.0 KiB + 110.0 KiB = 114.0 KiB	obexd
124.0 KiB +  21.5 KiB = 145.5 KiB	mpris-proxy
164.0 KiB +  24.0 KiB = 188.0 KiB	auditd
  4.0 KiB + 192.0 KiB = 196.0 KiB	address-book-service
192.0 KiB +  16.5 KiB = 208.5 KiB	subsystem_ramdump
212.0 KiB +  10.0 KiB = 222.0 KiB	upstart-property-watcher
212.0 KiB +  28.0 KiB = 240.0 KiB	rtkit-daemon
216.0 KiB +  31.0 KiB = 247.0 KiB	cron
236.0 KiB +  20.0 KiB = 256.0 KiB	servicemanager
244.0 KiB +  34.0 KiB = 278.0 KiB	ubuntu-location-provider-geoclue2
248.0 KiB +  36.5 KiB = 284.5 KiB	dconf-service
248.0 KiB +  40.5 KiB = 288.5 KiB	cgproxy
276.0 KiB +  30.0 KiB = 306.0 KiB	debuggerd
284.0 KiB +  24.0 KiB = 308.0 KiB	bluetoothd
216.0 KiB + 105.0 KiB = 321.0 KiB	ueventd
284.0 KiB +  39.5 KiB = 323.5 KiB	biometryd
336.0 KiB +   5.5 KiB = 341.5 KiB	healthd
312.0 KiB +  44.0 KiB = 356.0 KiB	lxc-start
324.0 KiB +  32.5 KiB = 356.5 KiB	lmkd
312.0 KiB +  44.5 KiB = 356.5 KiB	cgmanager
296.0 KiB +  75.5 KiB = 371.5 KiB	gnome-keyring-daemon
316.0 KiB +  55.5 KiB = 371.5 KiB	adbd
232.0 KiB + 142.5 KiB = 374.5 KiB	telepathy-ofono
336.0 KiB +  45.0 KiB = 381.0 KiB	chrome-sandbox (4)
336.0 KiB +  46.0 KiB = 382.0 KiB	dnsmasq
356.0 KiB +  31.5 KiB = 387.5 KiB	sh (3)
388.0 KiB +  22.0 KiB = 410.0 KiB	upstart-socket-bridge
356.0 KiB +  57.0 KiB = 413.0 KiB	su
384.0 KiB +  29.5 KiB = 413.5 KiB	upstart-local-bridge
240.0 KiB + 210.0 KiB = 450.0 KiB	evolution-addressbook-factory
440.0 KiB +  38.5 KiB = 478.5 KiB	rmt_storage
448.0 KiB +  32.5 KiB = 480.5 KiB	systemd-logind
288.0 KiB + 196.5 KiB = 484.5 KiB	telephony-service-handler
436.0 KiB +  54.0 KiB = 490.0 KiB	bridgemgrd
400.0 KiB +  96.0 KiB = 496.0 KiB	url-dispatcher
444.0 KiB +  56.0 KiB = 500.0 KiB	mpdecision
460.0 KiB +  44.5 KiB = 504.5 KiB	OwncloudSyncd
464.0 KiB +  48.0 KiB = 512.0 KiB	indicator-location-service
460.0 KiB +  61.0 KiB = 521.0 KiB	sshd
516.0 KiB +  45.5 KiB = 561.5 KiB	ofonod
512.0 KiB +  59.0 KiB = 571.0 KiB	indicator-network-secret-agent
524.0 KiB +  53.0 KiB = 577.0 KiB	qmuxd
528.0 KiB +  50.0 KiB = 578.0 KiB	indicator-bluetooth-service
496.0 KiB +  82.0 KiB = 578.0 KiB	upstart-dbus-bridge (2)
536.0 KiB +  69.5 KiB = 605.5 KiB	upstart-file-bridge (2)
300.0 KiB + 319.5 KiB = 619.5 KiB	qseecomd (2)
592.0 KiB +  60.5 KiB = 652.5 KiB	top
568.0 KiB +  95.5 KiB = 663.5 KiB	indicator-display-service
652.0 KiB +  41.0 KiB = 693.0 KiB	systemd-udevd
476.0 KiB + 221.5 KiB = 697.5 KiB	telephony-service-indicator
628.0 KiB +  76.0 KiB = 704.0 KiB	aethercast
672.0 KiB +  78.0 KiB = 750.0 KiB	urfkilld
696.0 KiB +  67.0 KiB = 763.0 KiB	netmgrd
740.0 KiB +  74.0 KiB = 814.0 KiB	zeitgeist-daemon
768.0 KiB +  66.5 KiB = 834.5 KiB	usermetricsservice
792.0 KiB +  48.0 KiB = 840.0 KiB	rsyslogd
816.0 KiB +  50.5 KiB = 866.5 KiB	wpa_supplicant
804.0 KiB +  89.0 KiB = 893.0 KiB	mtp-server
780.0 KiB + 148.5 KiB = 928.5 KiB	indicator-session-service
880.0 KiB +  48.5 KiB = 928.5 KiB	logd
920.0 KiB +  72.5 KiB = 992.5 KiB	miniafservice
900.0 KiB + 112.0 KiB =   1.0 MiB	mission-control-5
900.0 KiB + 138.5 KiB =   1.0 MiB	accounts-daemon
932.0 KiB + 113.5 KiB =   1.0 MiB	indicator-transfer-service
936.0 KiB + 136.5 KiB =   1.0 MiB	indicator-messages-service
944.0 KiB + 163.5 KiB =   1.1 MiB	upowerd
888.0 KiB + 243.5 KiB =   1.1 MiB	media-hub-server
  1.1 MiB +  19.5 KiB =   1.1 MiB	nuntium
  1.0 MiB + 113.0 KiB =   1.1 MiB	thermal-engine-hh
  1.1 MiB +  49.0 KiB =   1.2 MiB	usensord
892.0 KiB + 296.0 KiB =   1.2 MiB	evolution-source-registry
  1.0 MiB + 133.5 KiB =   1.2 MiB	Binder_2
  1.1 MiB + 112.0 KiB =   1.2 MiB	upstart-udev-bridge (2)
  1.2 MiB +  89.5 KiB =   1.3 MiB	upstart
  1.2 MiB +  86.0 KiB =   1.3 MiB	thumbnailer-service
  1.2 MiB +  95.0 KiB =   1.3 MiB	bash (2)
  1.2 MiB + 137.5 KiB =   1.3 MiB	whoopsie
  1.2 MiB + 198.5 KiB =   1.4 MiB	lightdm (2)
  1.2 MiB + 210.5 KiB =   1.4 MiB	indicator-keyboard-service
  1.2 MiB + 264.0 KiB =   1.4 MiB	account-polld
  1.2 MiB + 256.5 KiB =   1.5 MiB	pulseaudio
  1.4 MiB + 113.0 KiB =   1.5 MiB	sensors.qcom
  1.4 MiB + 110.5 KiB =   1.5 MiB	camera_service
  1.4 MiB + 175.0 KiB =   1.5 MiB	indicator-sound-service
  1.5 MiB + 223.0 KiB =   1.7 MiB	indicator-network-service
  1.7 MiB + 103.5 KiB =   1.8 MiB	zeitgeist-fts
  1.7 MiB +  21.5 KiB =   1.8 MiB	ciborium
  1.7 MiB + 106.0 KiB =   1.8 MiB	udisksd
  1.5 MiB + 331.5 KiB =   1.8 MiB	trust-stored-skeleton (3)
  1.7 MiB + 136.5 KiB =   1.8 MiB	polkitd
  1.7 MiB + 189.0 KiB =   1.9 MiB	content-hub-service
  1.8 MiB + 126.0 KiB =   1.9 MiB	indicator-power-service
  1.6 MiB + 384.0 KiB =   1.9 MiB	sudo (3)
  1.9 MiB + 163.0 KiB =   2.0 MiB	msyncd
  1.9 MiB + 191.0 KiB =   2.1 MiB	init (2)
  2.2 MiB + 175.0 KiB =   2.3 MiB	sync-monitor
  2.3 MiB + 211.0 KiB =   2.6 MiB	smartscopesproxy
  2.4 MiB + 268.0 KiB =   2.7 MiB	ubuntu-location-serviced
  2.4 MiB + 332.0 KiB =   2.7 MiB	repowerd
  2.7 MiB + 147.0 KiB =   2.8 MiB	rild
  3.0 MiB + 206.0 KiB =   3.2 MiB	scoperegistry
  3.0 MiB + 385.5 KiB =   3.3 MiB	dbus-daemon (2)
  3.2 MiB + 201.5 KiB =   3.4 MiB	NetworkManager
  3.6 MiB +  59.5 KiB =   3.7 MiB	mm-qcamera-daemon
  4.7 MiB +  18.5 KiB =   4.8 MiB	dhclient
  5.3 MiB + 241.0 KiB =   5.6 MiB	indicator-datetime-service
  6.0 MiB + 150.5 KiB =   6.2 MiB	ubuntu-push-client
  6.3 MiB + 197.0 KiB =   6.5 MiB	geoclue
  6.1 MiB + 673.5 KiB =   6.7 MiB	unity-system-compositor
 14.9 MiB + 673.0 KiB =  15.6 MiB	python3.4 (2)
 18.9 MiB +   1.2 MiB =  20.1 MiB	maliit-server
 20.8 MiB + 599.5 KiB =  21.4 MiB	system-settings
 25.0 MiB + 321.0 KiB =  25.3 MiB	evolution-calendar-factory
 58.3 MiB +   1.7 MiB =  59.9 MiB	cordova-ubuntu
 66.3 MiB +   1.7 MiB =  68.0 MiB	webapp-container
 97.8 MiB +   3.9 MiB = 101.8 MiB	qmlscene (2)
117.5 MiB +   1.0 MiB = 118.5 MiB	unity8-dash
274.1 MiB +   2.3 MiB = 276.4 MiB	unity8
314.4 MiB +  14.7 MiB = 329.1 MiB	oxide-renderer (11)
---------------------------------
                          1.1 GiB
=================================

Both results doesn't seem to match, 

Process wise, nothing goes above 40% of the CPU, and i see the kswap getting activated

**Comment by Flohack74** [comment]
Welcome to Ubuntu Touch where the OS takes up to 90% of available RAM...

**Comment by ernesst** [comment]
Ahah, 
So, my swap is full too :)

**Comment by doniks** [comment]
As far as I can tell, UT has always used all 2 GB ram on my device. Also, out of the box it _has_ barely any swap space and _uses_ even less. Instead it just kills apps. But it can be hacked to behave differently: https://forum.xda-developers.com/ubuntu-touch/help/stopping-ut-killing-apps-t3424764

**Comment by mariogrip** [comment]
reverted some systemd changes to the kernel, this seems to fix the issue: https://github.com/ubports/android_kernel_lge_hammerhead/commit/65d4ccac73e2785e63e3d63b818f43bcc6494d9c

Please let me know if this fixed the issue

**Comment by NeoTheThird** [comment]
All seems to be back to normal. Looks good!

**Comment by mariogrip** [comment]
Reported fixed

**Comment by ernesst** [comment]
Just back, just flashed
The performance looks much better, however : 
- The boot takes ages to get the Ubport logo
- Lot of websites shown an certificate issue : Ubport forum, ebay, reddit etc...

**Comment by ernesst** [comment]
I can confirm, the perf are really nice now. Thanks for the fix
