### ISSUE TITLE
Missing /system/media/audio/ui files in FP2

### ISSUE THREAD

**Issue by vigotron** [ubports/ubports-touch#180]
Story:
While using camera app and taking screenshots I missed the audios, seems like /ui audio files aren't there in FP2, however they are in Krillin.

Environment:
-# system-image-cli -i
current build number: 7
device name: FP2
channel: ubports-touch/15.04/devel
last update: 1970-04-13 12:39:17
version version: 7
version ubports: 20170531-13919
version keyring: archive-master
version device: 20170531-21104

Steps to reproduce:

1º Open camera app 
2º Take a pic or record video
3º Make a screenshot by pressing both volume buttons(+ & -)

Actual result: some audios missing from actions like taking screenshots, photos, record & stop record audios etc

Expected result: have back /ui audio files 

![fp2_ui_audio](https://user-images.githubusercontent.com/30204049/28546567-70959cec-70cb-11e7-859c-16447d8fa875.png)
![krillin_ui_audio_files](https://user-images.githubusercontent.com/30204049/28546568-70954260-70cb-11e7-8740-743f2967cc7f.png)

**Comment by mariogrip** [comment]
Fix pushed https://github.com/ubports/android_vendor_cm/pull/1
