### ISSUE TITLE
Disonnect tone too loud

### ISSUE THREAD

**Issue by vigotron** [ubports/ubports-touch#181]
Story:
Sometimes when the remote party hungs up the call and the phone is still in my ear I realize that disconnect tone is a bit annoying. I checked on krillin and other android device and it's way lower there, I would like to know if any other user experienced this too

Environment:
-# system-image-cli -i
current build number: 7
device name: FP2
channel: ubports-touch/15.04/devel
last update: 1970-04-13 12:39:17
version version: 7
version ubports: 20170531-13919
version keyring: archive-master
version device: 20170531-21104

Steps to reproduce:

1º Make a phone call
2º Wait until the other party hungs up

Current result: disconnect tone in FP2 is a bit louder than other phones
Expected result: disconnect tone adjusted like the other phones

**Comment by bastos77** [comment]
Same at my Fairphone. I can confirm the same behaviour.
In addition if I get a call waiting signal while doing a phone call (Anklopf Signal) this is also much too loud.
Those two bugs maybe could be solved with the same adjustment.

**Comment by bastos77** [comment]
I have already reported this in issue #49
