### ISSUE TITLE
Remove language "C"

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-touch#182]
For some reason, a language "C" shows up in the list of languages on first setup.

**Comment by garro95** [comment]
May be an easter egg for programmers?

**Comment by NeoTheThird** [comment]
Maybe, but nothing is translated to it, so everything just shows as English. It just causes confusion imho.

**Comment by Flohack74** [comment]
While researching the possible addition of Sardinian to the phone, it became now clear why C showed up: This is actually a language pack which Qt cannot resolve into a language_COUNTRY pair. So in this case, C and en are being used. I disabled the warning on a test branch again. So the original fix would have been to either remove the language pack in question or fix Qt upstream: https://bugreports.qt.io/browse/QTBUG-57802
