### ISSUE TITLE
Only show 2nd SIM card indicator if there is a SIM card present

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubports-touch#185]
The second empty SIM card symbol shows up on all phones with 2 SIM slots. This wasnt the original behaviour, but Canonical decided to always show this indicator later on.

I vote for not displaying any empty SIM card symbol IF the phone has more than 1 SIM slot. Advantage: Cleaner top bar, many users never use 2 SIM cards.
Disadvantage: If a SIM card fails, there will be no symbol for it but just the indicator disappears. But to me "no indicator" has the same level of information than "empty slot indicator".

Maybe we even extend it to 1 slot phones also. "empty slot indicator" has really not much information. If the users sees no indicator but a card is inside, smth is wrong with the hardware or the SIM card, and he will start looking for it.

**Comment by mihaelmilea** [comment]
In my Meizu Pro 5 I have a micro SD card inserted in the first sim card slot. I would prefer instead of an empty sim card icon to have a symbol that shows an SD card is inserted. Maybe even active (more white in the icon) when read/write happens on the SD card. Or maybe even better to have in white the amount of used space on the SD card.

**Comment by Flohack74** [comment]
Good point but somehow unrelated: The SIM and SD card are handled by different services in the background. So one thing is how we handle SIM cards, the other one: We need a new concept for SD cards, yes. The current system setting does not much, and the icon is ugly. I can envision an "removable-media-indicator" that does exactly what you described.

**Comment by Flohack74** [comment]
This issue was moved to ubports/indicator-network#1
