### ISSUE TITLE
Hammerhead - Devel : GPS getting stuck

### ISSUE THREAD

**Issue by ernesst** [ubports/ubports-touch#186]
I've noticed with the recent devels the gps apps got stuck and time to time Unav see it's permission revoked during a guidance. 
I'm back to rc for further tests, to unsure it's from Devel.

**Comment by Flohack74** [comment]
Ok can you tell us then if you can confirm the problem is in current devel? No one touched GPS I think... @mariogrip ?

**Comment by ernesst** [comment]
My last try on the devel was ok, i switched back to rc for my holidays. I'll try back in september.

**Comment by NeoTheThird** [comment]
Ok, thanks. Let's close this for now.
