### ISSUE TITLE
Terminal and Filebrowser not preinstalled

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-touch#2]
System apps like the File-browser and Terminal app are not preinstalled at the moment meaning that with out adb working there is no command line access to the OS. A serious fault in my opinion.

This was originally reported by https://launchpad.net/~j-apple-muncy.

**Comment by NeoTheThird** [comment]
Maybe all core apps that have a maintainer and have been moved to the openstore should be preinstalled?

**Comment by Flohack74** [comment]
I think this is a good idea, at least I see no negative impacts :)

**Comment by mariogrip** [comment]
Fix released
