### ISSUE TITLE
GPS not working

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-touch#20]
Gents,
With the image 2017041968380 the GPS is not working :

root@ubuntu-phablet:~# test_gps
*** setup signal handler
*** get gps interface
*** device info
 id = gps
 name = loc_api GPS Module
 author = Qualcomm USA, Inc.
*** init gps interface
 ** Creating thread: 'Loc_hal_worker' (start=0xb6ba77c5, arg=0x1ceba70)
 ** After thread_create: 'Loc_hal_worker', error=0 (start=0xb6ba77c5, arg=0x1ceba70)
 **** Thread wrapper start (start=0xb6ba77c5, arg=0x1ceba70) ****
 Diag_LSM_Init: Failed to open handle to diag driver, error = 2*** setting positioning mode
*** start gps track
*** gps tracking started
*** tracking....
*** status callback
*** session begin
*** set capabilities
capability is 00000007
*** status callback
*** engine on
*** status callback
*** session begin

Some other input :
# tail -f /userdata/system-data/var/log/upstart/ubuntu-location-service.log
 Diag_LSM_Init: Failed to open handle to diag driver, error = 2 Diag_LSM_Init: Failed to open handle to diag driver, error = 2Instantiating and configuring: remote::Provider
Attempted to unregister path (path[0] = com path[1] = ubuntu) which isn't registered
Attempted to unregister path (path[0] = org path[1] = freedesktop) which isn't registered
Attempted to unregister path (path[0] = org path[1] = freedesktop) which isn't registered
Attempted to unregister path (path[0] = core path[1] = trust) which isn't registered
 name -> com.ubuntu.espoo.Service.Provider
 path -> /com/ubuntu/espoo/Service/Provider
Instantiating and configuring: gps::Provider
 Diag_LSM_Init: Failed to open handle to diag driver, error = 2Instantiating and configuring: remote::Provider
Attempted to unregister path (path[0] = com path[1] = ubuntu) which isn't registered

Regarding the error msg : Diag_LSM_Init: Failed to open handle to diag driver, error = 2

I've found a similar error msg for Firefox OS and Nexus 5
https://bugzilla.mozilla.org/show_bug.cgi?id=1107742
They fixed it by the commit in the bug https://bugzilla.mozilla.org/show_bug.cgi?id=1112175

It's seems a permission issue defined in BoardConfig.mk
https://github.com/mozilla-b2g/device-hammerhead/commit/98e8bed41f06d62373146054c5e7b328d93d6582

-BOARD_KERNEL_CMDLINE := console=ttyHSL0,115200,n8 androidboot.hardware=hammerhead user_debug=31 maxcpus=2 msm_watchdog_v2.enable=1 androidboot.selinux=disabled
+BOARD_KERNEL_CMDLINE := console=ttyHSL0,115200,n8 androidboot.hardware=hammerhead user_debug=31 maxcpus=2 msm_watchdog_v2.enable=1 androidboot.selinux=permissive

It's so far out of my capabilities to assess if this is applicable or not.

Rgds

And the last log i can pull is :

less /var/log/syslog |grep gps
ubuntu-phablet kernel: [ 1024.272978] msm_ipc_router_send_to: permission failure for test_gps

This msg makes me think the proposed solution could help.

Interesting point;

I cannot diagnostic the gps as mentioned above, but today the GPS worked !
So i've tried with success Unav and acrivity tracker.

So if possible we can change the bug title as "impossible to diagnose Gps".

Hi,

Still no GPS working for me, even after recent update... Not an expert but if someone can tell me how to log from my phone, I'll be happy to participate.

Jean-Paul,

Simple verification
Did you try to launch Unav for instance outside, not under a roof, without a protection for your phone and wait up to 10 min ?

Otherwise you can generate, via adb_shell :
less /var/log/syslog |grep gps
tail -f /userdata/system-data/var/log/upstart/ubuntu-location-service.log
test_gps

But in my case the output is negatif while the GPS works.

reported by https://launchpad.net/~slash-tux

**Comment by Flohack74** [comment]
I got now:

```
root@ubuntu-phablet:~# test_gps 
*** setup signal handler
*** get gps interface
*** device info
 id = gps
 name = loc_api GPS Module
 author = Qualcomm USA, Inc.
*** init gps interface
 ** Creating thread: 'Loc_hal_worker' (start=0xb6bd07c5, arg=0x1537a70)
 ** After thread_create: 'Loc_hal_worker', error=0 (start=0xb6bd07c5, arg=0x1537a70)
 **** Thread wrapper start (start=0xb6bd07c5, arg=0x1537a70) ****
 Diag_LSM_Init: Failed to open handle to diag driver, error = 2*** setting positioning mode
*** start gps track
*** gps tracking started
*** tracking.... 
*** status callback
*** session begin
*** set capabilities
capability is 00000007
*** tracking.... 
*** tracking.... 
*** tracking.... 
```

So this looks different. Did not try outside actually, but lets test this as well.

**Comment by Flohack74** [comment]
I close this for now, GPS seems OK:

```
*** sv status
sv_size:	0
num_svs:	16
	 azimuth:	284.000000
	 elevation:	29.000000
	 prn:	1
	 size:	660
	 snr:	19.500000
	 azimuth:	292.000000
	 elevation:	45.000000
	 prn:	11
	 size:	660
	 snr:	21.500000
	 azimuth:	229.000000
	 elevation:	26.000000
	 prn:	22
	 size:	660
	 snr:	13.900000
	 azimuth:	0.000000
	 elevation:	0.000000
	 prn:	3
	 size:	660
	 snr:	0.000000
	 azimuth:	222.000000
	 elevation:	70.000000
	 prn:	8
	 size:	660
	 snr:	0.000000
	 azimuth:	56.000000
	 elevation:	45.000000
	 prn:	10
	 size:	660
	 snr:	0.000000
	 azimuth:	136.000000
	 elevation:	29.000000
	 prn:	14
	 size:	660
	 snr:	0.000000
	 azimuth:	326.000000
	 elevation:	59.000000
	 prn:	85
	 size:	0
	 snr:	22.500000
	 azimuth:	194.000000
	 elevation:	46.000000
	 prn:	70
	 size:	0
	 snr:	0.000000
	 azimuth:	312.000000
	 elevation:	7.000000
	 prn:	86
	 size:	0
	 snr:	0.000000
	 azimuth:	5.000000
	 elevation:	6.000000
	 prn:	77
	 size:	0
	 snr:	0.000000
	 azimuth:	312.000000
	 elevation:	10.000000
	 prn:	76
	 size:	0
	 snr:	0.000000
	 azimuth:	57.000000
	 elevation:	66.000000
	 prn:	69
	 size:	0
	 snr:	0.000000
	 azimuth:	112.000000
	 elevation:	57.000000
	 prn:	84
	 size:	0
	 snr:	0.000000
	 azimuth:	126.000000
	 elevation:	4.000000
	 prn:	83
	 size:	0
	 snr:	0.000000
	 azimuth:	33.000000
	 elevation:	16.000000
	 prn:	68
	 size:	0
	 snr:	0.000000
*** nmea info
timestamp:	-960888282
nmea (67): 	$GPGSV,2,1,07,01,29,284,20,11,45,292,22,22,26,229,14,03,00,000,*78
*** nmea info
timestamp:	-960888281
nmea (50): 	$GPGSV,2,2,07,08,70,222,,10,45,056,,14,29,136,*4A
*** nmea info
timestamp:	-960888281
nmea (63): 	$GLGSV,3,1,09,85,59,326,23,70,46,194,,86,07,312,,77,06,005,*6A
*** nmea info
timestamp:	-960888280
nmea (61): 	$GLGSV,3,2,09,76,10,312,,69,66,057,,84,57,112,,83,04,126,*66
*** nmea info
timestamp:	-960888280
nmea (28): 	$GLGSV,3,3,09,68,16,033,*55
*** nmea info
timestamp:	-960888279
nmea (29): 	$GPGSA,A,1,,,,,,,,,,,,,,,*1E
*** nmea info
timestamp:	-960888278
nmea (24): 	$GPVTG,,T,,M,,N,,K,N*2C
*** nmea info
timestamp:	-960888278
nmea (24): 	$GPRMC,,V,,,,,,,,,,N*53
*** nmea info
timestamp:	-960888277
nmea (25): 	$GPGGA,,,,,,0,,,,,,,,*66
```
