### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by Marathon2422** [ubports/ubports-touch#203]
Enhancements rework the Browser,so the search engine page,shows UBports for all the links instead of Ubuntu,redirect here the wiki,and so forth

**Comment by gnulinuxuser** [comment]
Ubports developers, can you guys add option or ability  to make  the apps,scope background transparent. For example If I select  a picture from system -->settings--->background, I need to be able yo see it on the main screen ( home )

**Comment by NeoTheThird** [comment]
I will close this issue now, as it does not target specific bugs or enhancements. If you're interested, you [can read our guide on writing a good bug report](https://wiki.ubports.com/wiki/Writing-a-Good-Bug-Report). Thank you :)

@Marathon2422 Some generic ubuntu links, like the one in the system indicator ( #175 ) have already been replaced with UBports and Ubuntu Touch specific links and will be shipped in OTA 2.

@gnulinuxuser That is already implemented ( #104 ) and will be shipped in OTA 2.

**Comment by ChloeWolfieGirl** [comment]
Thanks NeoTheThird
