### ISSUE TITLE
Brower has no tabs 

### ISSUE THREAD

**Issue by mariogrip** [ubports/ubports-touch#209]
- Device: bq M10 HD and FHD
- Channel: 15.04/devel

## Steps to reproduce

1. open browser

**Comment by NeoTheThird** [comment]
I can confirm this for the M10 HD as well.

**Comment by TronFourtyTwo** [comment]
I can confirm it for One Plus One (in Desktop view).
The problem is the missing QML Ubuntu.Components.Extras 0.3 from the vivid images, wich contains the tabs stuff.

**Comment by NeoTheThird** [comment]
Thanks @TronFourtyTwo. So this is device agnostic.

**Comment by Flohack74** [comment]
Can we add this @TronFourtyTwo ?

**Comment by NeoTheThird** [comment]
@Flohack74 Marius was looking into it. We forked the repo to https://github.com/ubports/ubuntu-ui-extras, but launchpad is yet running into build errors.

**Comment by mariogrip** [comment]
Fix released https://github.com/ubports/ubuntu-ui-extras/commit/c0b943ad87fff87eb7bbeb156f56a2b958389e3b

It's landed in the dev ppa

Also made some simple scripts for testing the dev ppa
https://github.com/mariogrip/qa-scripts
