### ISSUE TITLE
Updates setting spell typo

### ISSUE THREAD

**Issue by ernesst** [ubports/ubports-touch#234]
- Device: All
- Channel: Devel
- Build: latest

In the updates menu, the "update settings" is written "update settngs"

**Comment by Flohack74** [comment]
Yeah @mariogrip knows already ;)

**Comment by Flohack74** [comment]
Guys, its an easy task, I just need the updated .pot file committed here. Only pot, no po plz. It takes about 10mins ;) but please we need to do it so that translators have time to translate it.

**Comment by nfsprodriver** [comment]
This issue itself seems to be solved in latest devel image (tested on N5) so it can be closed.

**Comment by Flohack74** [comment]
Yeah thats true but still the string will not be translated in the final version unless we update the pot file in Github. We need a good process for the future to make this possible. Currently continous integration is not supposed to feed back the pot files to Github, thats a task of the developer.
