### ISSUE TITLE
No keyboard when writing new email

### ISSUE THREAD

**Issue by rubencarneiro** [ubports/ubports-touch#236]
- Device: hammerhead
- Channel: Devel
- Build: Xxx

## Steps to reproduce

1. ...
2. ...
3. ...

## Expected behavoir

...

## Actual behavior

...

## Logfiles and additional information

...

**Comment by rubencarneiro** [comment]
Keyboard not showing when writing email, have to pull down notification bar, then keyboard apperas.

**Comment by dark-eye** [comment]
@rubencarneiro I think this  issue should be under : https://gitlab.com/dekkoproject/dekko/issues

**Comment by Scym1** [comment]
I think this is a OS problem and not a Dekko problem. The same thing happens when you start a private window in the browser. No keyboard. And the solution is the same, put the app in the background and come back. The keyboard pop up then.

**Comment by dark-eye** [comment]
Oh right sorry @rubencarneiro ...

**Comment by Flohack74** [comment]
This is related to #52 - We soon need to define the component where we track this, or find the real reason at least.
