### ISSUE TITLE
 Loss of GPS permission randomly 

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-touch#24]
Dear,

On my Nexus r298 the GPS works well and quite fast to get the signal. However i've noticed that randomly Unav for instance during the navigation it loosing the GPS permission.
A reboot of the phone does the trick.

reported by https://launchpad.net/~slash-tux.

**Comment by ernesst** [comment]
Since i switched to legacy, 2 weeks ago i didn't meet the problem anymore. 
I guess can be closed until further notice.
