### ISSUE TITLE
Libertine

### ISSUE THREAD

**Issue by fmulcar** [ubports/ubports-touch#248]
Nexus 4
Channel devel 
Revision 139
Desktop apps dont initiate

**Comment by NeoTheThird** [comment]
I'm sorry, but a bugreport needs *a lot* more information than this. This is not the first time you posted a report like this, and it causes more work than it helps. Please read the [guide on writing a good bugreport](https://wiki.ubports.com/wiki/Writing-a-Good-Bug-Report) and act by its recommendations in the future.

I appreciate that you want to help by reporting bugs, but a report like this does not really help.
