### ISSUE TITLE
Can't add comments in some website forums/discussions using Disqus, website crashes( in convergence mode it works normally (turbo) )

### ISSUE THREAD

**Issue by Stefano0101** [ubports/ubports-touch#254]
- Device: Turbo/ Hammerhead
- Channel: 15.04 rc
- Build: 4/5

## Steps to reproduce

1. ...Trying to comment on some websites articles and it's not possible
2. ...The website crashes and displays " The rendering process has been closed for this tab" " something went wrong while displaying https://....."
3. ...Gives you option to close tab or reload

## Expected behavoir

... it should be possible to add comments on website articles just as before the browser update 

## Actual behavior

... but in some website it's not
![screenshot20170920_101756743](https://user-images.githubusercontent.com/29058699/30637285-d1685ca2-9def-11e7-9f98-9d8ac813149c.png)

## Logfiles and additional information

...I have tried to disable uAdblock, but the issue persist 
**BUT, I just tried to connect to external display with TURBO, in convergence mode via Aethercast and it works normally, so go figure????**

**Comment by Flohack74** [comment]
This is probably out of memory issue...

**Comment by Stefano0101** [comment]
Also when playing a video on website, the browssr crashes with the same message.

**Comment by Stefano0101** [comment]
I have cleared the cache of Browser, where normally is there like 20-50MB , now there was 287 MB in cache. It doesn't seems to be right to have a such amount data in cache, something's wrong with the new Browser.

**Comment by Stefano0101** [comment]
This can be closed down as the browser in OTA-2 works just great, no more such a crashes

**Comment by Flohack74** [comment]
Hmm that always frightens me, we did not change anything with the browser =)

**Comment by Stefano0101** [comment]
If I observe any more  behavior like stated above, I'll fill a new bug report.
