### ISSUE TITLE
Mako - Screen not locking

### ISSUE THREAD

**Issue by ernesst** [ubports/ubports-touch#260]
- Device: Mako
- Channel: Devel
- Build: 144

## Steps to reproduce

Set q timing for locking the screen

## Expected behavoir

Screen going black

## Actual behavior

screen stay alive

**Comment by ernesst** [comment]
After couple of reboot, the screen lock according to the settings.

**Comment by chriscroome** [comment]
I also has this issue and solved it by [reflashing the phone](https://forums.ubports.com/topic/1010/lock-screen-doesn-t-lock/5).
