### ISSUE TITLE
Cursor control in OSK Space Bar (Silo # 2351)

### ISSUE THREAD

**Issue by kugiigi** [ubports/ubports-touch#265]
- Device: bq E5 HD
- Channel: Stable
- Build: OTA-2

## Expected behavoir
Long pressing the space bar will activate the function to move the cursor by swiping the space bar horizontally or vertically

## Logfiles and additional informatiom
This has been initially implemented before Ubuntu Touch was dropped by Canonical.
Silo # 2351 holds the initial code for this.

**Comment by mariogrip** [comment]
@Elleo Is this something that is ready to merge?

**Comment by Elleo** [comment]
Yep, it's already in the keyboard-component master it just needs a release :)

**Comment by mariogrip** [comment]
There we go! it's now building :D It will land in devel pretty soon! Thanks @Elleo!
