### ISSUE TITLE
Can't update

### ISSUE THREAD

**Issue by giovanoiannotti** [ubports/ubports-touch#266]
- Device:update Bq4.5
- Channel: ubports-touch/15.04/rc
- Build: 3

## Steps to reproduce

1. Go to Settings
2. Go to Update
3. Settings will crash and close

## Expected behavoir

Check for updates
...

## Actual behavior

It crashes

## Logfiles and additional information

...

**Comment by giovanoiannotti** [comment]
current build number: 3
device name: krillin
channel: ubports-touch/15.04/rc
last update: 2017-09-11 21:33:58
version version: 3
version ubports: 20170904-13114
version keyring: archive-master
version device: 20170512-1010

**Comment by giovanoiannotti** [comment]
Hi Mario,

which logs are needed and how do I get them?

**Comment by UniversalSuperBox** [comment]
The logs we need are in /var/log/system-image/

**Comment by giovanoiannotti** [comment]
Sorry, guys. Can't reproduce it anymore. I had to reflash the OS. Will close the issue.
