### ISSUE TITLE
Browser restarts every time

### ISSUE THREAD

**Issue by giovanoiannotti** [ubports/ubports-touch#267]
- Device: Bq 4.5
- Channel: ubports-touch/15.04/rc
- Build:3

## Steps to reproduce

1. Open the browser
2. Open websites on one or more tabs
3. Change the focus to another app or close the browser and reopen it or restart the system
4. Browser starts from the Ubuntu / Google default initial page.
PS: I have obviously chosen the option to restart from where I left it

## Expected behavoir

Start with the tabs I had open bwfore
...

## Actual behavior

starts from default Page

## Logfiles and additional information

...

**Comment by giovanoiannotti** [comment]
current build number: 3
device name: krillin
channel: ubports-touch/15.04/rc
last update: 2017-09-11 21:33:58
version version: 3
version ubports: 20170904-13114
version keyring: archive-master
version device: 20170512-1010

**Comment by giovanoiannotti** [comment]
Using UT tweak tool, I have chosen the option 'prevent closing app' (not sure about the English precise terms). Apparently, this made the Browser behave normally.

**Comment by giovanoiannotti** [comment]
![screenshot20170925_074437543](https://user-images.githubusercontent.com/32245412/30794097-8de41644-a1c6-11e7-8d28-16591fc6c7f0.png)
![screenshot20170925_074454448](https://user-images.githubusercontent.com/32245412/30794098-8df45c8e-a1c6-11e7-9e84-33b31c29e2e0.png)

**Comment by simoxxx** [comment]
This can be also due to the low ram memory these devices are shiped with..you may close this issue..

**Comment by giovanoiannotti** [comment]
Sorry, guys. Can't reproduce it anymore. I had to reflash the OS. Will close the issue.
