### ISSUE TITLE
Uninstall indicator torch not working

### ISSUE THREAD

**Issue by bqphone** [ubports/ubports-touch#274]
- Device: bq e4.5
- Channel:stable
- Build:r2

## Steps to reproduce

1. ...
2. ...
3. ...

## Expected behavoir

I did install torch indicator app from openstore, and after i tried it i did uninstall it, but for some reason i still see in my notification toolbar nfsprovider-indicator-torch, even after i did restart the phone.

My question is how i can get rid of that and totally remove it from my phone.

## Actual behavior

...

## Logfiles and additional information

...

**Comment by sverzegnassi** [comment]
Indicator Torch is one of those "hacks" available on OpenStore, which does not follow the Ubuntu confinement specifications; therefore, the tool is able to install new indicators on the system - standard .click packages would not be able to do so.

My suggestion is to reinstall the package from the OpenStore: from the Applications scope, you can find the companion app and uninstall the torch indicator. Then, you can safely remove the package from the system, without any trace of a torch in the status bar.

Please note that Indicator Torch is a third party package, therefore the question does not belong directly to the UBports project.

I'm going to close this report, you will still be able to reply to my comment if anything went wrong. :)
