### ISSUE TITLE
Password for WiFi not saved / Automatic reconnection to WiFi not possible

### ISSUE THREAD

**Issue by HaleyACS** [ubports/ubports-touch#280]
- Device:BQ E 4.5
- Channel: rc
- Build:Ubuntu 15.04 r6 / 20170512-1010

FYI -  the WiFi password is a passphrase with spaces. Had that issue with other Linux devices in the past.

## Steps to reproduce

1. Access SSID/Network, enter password (expect it to be saved) - check you're connected.
2. reboot device or switch to airplane mode, wait 10secs and switch back to networked mode.
3. While on the same network, it won't automatically reconnect. Note that the WiFi settings are stored, as I can delete these from the previous networks list.

## Expected behavoir
The Password to be stored and WiFi usable after a reboot or switching back to network mode after Ariplane mode.

## Actual behavior
WiFi is not automatically reconnected. Also selecting a previously known network which has the password stored, is not working. The Password needs to be put in again.

## Logfiles and additional information
[UTdmesg.txt](https://github.com/ubports/ubports-touch/files/1343305/UTdmesg.txt)
[UTlogcat.txt](https://github.com/ubports/ubports-touch/files/1343307/UTlogcat.txt)

...

**Comment by doniks** [comment]
Duplicate of this? https://github.com/ubports/ubports-touch/issues/252

**Comment by HaleyACS** [comment]
Yes and no. I tested a little further and found out that putting the Airplane mode on and off has the same effect.
Didn't find that one first though.
But OK - let's call it a duplicate ;)
