### ISSUE TITLE
OSK does not work in private browsing window

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-touch#3]
The keyboard does not work in pirvate browsing windows.

This was originally reported by https://launchpad.net/~nithinrao.

https://launchpad.net/~ahayzen points out:

This sounds very similar to [bug 1623861](https://bugs.launchpad.net/bugs/1623861), which was when switching quickly between two windows of the same application (only webbrowser-app supports multiple windows for now :-) ), if you do a 'quick swipe' (eg where you drag from the right a bit, release and it switches straight to the second window) rather than a full swipe to switch between the windows by selecting from the switcher. It would result in the focus being broken (eg keyboard not appearing).

I wonder what version of qtubuntu you have on the device, as this should have been fixed, or maybe it is still racy on a faster device.

**Comment by rubencarneiro** [comment]
Actually it works, as long you close all the non private browser windows

**Comment by NeoTheThird** [comment]
Ohh, that's a good tip, thx Ruben.

**Comment by userj** [comment]
This is confirmed on bacon device as well

**Comment by NeoTheThird** [comment]
It also affects FP2, so it's probably device agnostic.

**Comment by Stefano0101** [comment]
same on Meizu Pro 5

**Comment by NeoTheThird** [comment]
Duplicate of #52.
