### ISSUE TITLE
Cannot access camera when app returns to foreground

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-touch#31]
Camera shows no permissins granted. Seems random. Pops window to cancel or change permissions under settings, but options are greyed out (applications allowed to access camera under settings for security and privacy). Also blocks access for other apps using the led flash, like Torch or Morse Sender.

reported by https://launchpad.net/~mgc.lude

I can confirm that this happens on a fresh, newly wiped device running devel_rc-proposed r291. The Camera app throws the "Cannot access camera" whenever it tries to resume its access.

To reproduce:
Open the Camera app
Confirm that you can use the viewfinder and do camera-y things
Move to a different app (even moving to the app switcher works) so the app releases the camera
Move back to the camera app
Get the "Cannot access camera" Error.

Workaround:
Close the app by swiping it away
Reopen the app

Someone in the Telegram channel guessed this is because the app does not release the camera properly when it is deactivated.

There are some times when the camera will resume while the error is visible. Clicking Cancel on the dialog box then lets you continue using the camera.

https://bugs.launchpad.net/ubports-fp2/+bug/1669905/+attachment/4873818/+files/camera.log
https://bugs.launchpad.net/ubports-fp2/+bug/1669905/+attachment/4873836/+files/cameralogcat.log

added by https://launchpad.net/~universalsuperbox

**Comment by vigotron** [comment]
Please find below some logs attached: 
Time stamps: 12:40 and 12:43 
[logs+prompt message.zip](https://github.com/ubports/ubports-touch/files/1150706/logs.prompt.message.zip)

**Comment by mariogrip** [comment]
Fix pushed https://github.com/ubports/android_kernel_fairphone_fp2/commit/3666dc344782c212fe62a144a1cd5b6f96da31c0

Thanks to @peat-psuwit for pointing this our!
