### ISSUE TITLE
 Browser and webapps don't work when connected to a display

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-touch#4]
The browser and webapps do not open, when the device is connected to an external monitor. Confirmed for M10 HD, M10 FHD and Nexus 5.

This was first discovered here: https://forums.ubports.com/topic/194/convergence

**Comment by NeoTheThird** [comment]
This might be caused by #80.

**Comment by mymike00** [comment]
could this be closed as this is fixed, or you're waiting for OTA-2 on stable?

**Comment by NeoTheThird** [comment]
Thanks for the reminer @mymike00, forgot to do it :)
