### ISSUE TITLE
browser "bounces" when scrolling

### ISSUE THREAD

**Issue by userj** [ubports/ubports-touch#43]
Device: bacon
Channel: legacy
Version: Ubuntu 15.04 r13

What happens:
Web page in browser "bounces" up or down when scrolling (often in the opposite direction of the intended scroll). This is especially the case when the page is still loading or just finishes loading. It does sometimes seem to be web page-dependent, but most non-simple websites experience this issue.

What is expected to happen:
Smooth scrolling in direction of the scroll.

Steps to reproduce:
1. Visit a website on the browser app
2. Start swiping up and/or down 

Notes:
This has been a long-standing issue with Ubuntu touch, which I experienced on the mako as well.

**Comment by NeoTheThird** [comment]
I can see tiny spikes on multiple devices, but nothing huge. What page do you see this issue on?

**Comment by userj** [comment]
Perhaps the spikes are tinier than I imagine. 

Some sites that I see it on:
starwars.com
youtube.com
ubports.com (some parts with more load times)

Basically sites that have more content to load. There also seems to be a positive correlation to sites that need to change to the "mobile version" of the site. However, youtube.com displays as the desktop version.

It also seems to be that *first* scroll attempt where it mostly lags, and then rockets one way or another.

Sites that don't have a problem:
google.com (but it displays the desktop version instead of the mobile version)

**Comment by Flohack74** [comment]
I can confirm this, it always existed for me since I use UT. Its bad multitasking prioriry in the browser, loading a page blocks the gui thread. Not easily fixable

**Comment by Flohack74** [comment]
This issue was moved to ubports/webbrowser-component#6
