### ISSUE TITLE
 Permanent reboot tries after battery drain 

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-touch#50]
legacy 15.04 r14:after automatic shutdown due to power shortage, my FP2 permanently tries to reboot if plugged to a charger. But die due to no power. And that is happening again and again.
Only with a powerful charger after 100 of reboots it comes back.

Workaround: boot into recovery (power and volume up) will calm down situation and battery can get charged until minimum

Reported by https://launchpad.net/~sebastian-gallehr

**Comment by peat-psuwit** [comment]
Does the battery indicator appear? If yes, then it's probably a duplicate of #34.

**Comment by bastos77** [comment]
Here also the batery sign shortly is visible. And -surprise!- The LED has activity!

**Comment by peat-psuwit** [comment]
Then I think it's #34. Marking this as duplicate.
