### ISSUE TITLE
 Access to gps denied after app comming back into foreground 

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-touch#51]
15.04 legacy r14: Unav unable to get access to gps after coming back from background. Only rebooting my fp2 has helped

Reported by https://launchpad.net/~sebastian-gallehr

**Comment by bastos77** [comment]
legacy r20: Seems not to be the case anymore. GPS and AGPS is more than fine.

**Comment by bastos77** [comment]
Semms to  be fixed with OTA 2. Have not observed this issue anymore

**Comment by Flohack74** [comment]
Ok thx ;)
