### ISSUE TITLE
Screen unlock by fingerprint doesn't work

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-touch#54]
I'm testing the UBports image* for the pro5-turbo device and I noticed that unlocking the screen using the fingerprint doesn't work.
It may not be a bug and hasn't yet been added to the image, since it's not in the unlocking possibilities in system settings.

*image version: 1 (http://system-image.ubports.com/ubports-touch/legacy/turbo/);

Reported by https://launchpad.net/~aitzol76.

**Comment by mariogrip** [comment]
Fix released
