### ISSUE TITLE
difficulty in accessing lower/bottom edge

### ISSUE THREAD

**Issue by userj** [ubports/ubports-touch#55]
**Device: Bacon
Channel: Legacy
Version: Ubuntu 15.04 (r13)**

**What happens:**
When swiping up from the bottom edge, the system either lags or does not register the swipe immediately. The touch target seems very specific. Sometimes requires either waiting or multiple swipes or more accurate swipes.

**What is expected:**
Bottom swipe recognized quicker every time.

**Steps to repeat (various):**
(A) Access the quick settings pull down. Then try to close it by swiping up from below the little "3 dot" tab. Then try swiping right on the "3 dots"
(B) In browser app. Try to access the "tabs" tab at the bottom with the same actions as (A)

**Comment by NeoTheThird** [comment]
I can't really reproduce it. You might want to try not swiping up exactly in the middle. The button on the Opo can make swiping a little wonky.

**Comment by Flohack74** [comment]
Are you on the latest UBports image? r13 sounds like Canonical

**Comment by NeoTheThird** [comment]
@Flohack74 There's no bacon image from canonical. r13 is a possible build number on the legacy channel.

**Comment by mariogrip** [comment]
This is an issue only only on opo

**Comment by userj** [comment]
@NeoTheThird  Yes, it does seem to be the opo middle home button area that is an issue, but that visual tab in the middle makes me want to swipe right in the middle.

**Comment by NeoTheThird** [comment]
Maybe it would be possible to just disable the middle button...

**Comment by tomoqv** [comment]
+1 on this, but I am learning to handle it. Still kind of annoying though.

**Comment by userj** [comment]
I have actually been experiencing this issue when NOT swiping right in the middle too. It is something with the bottom edge on the opo, which is larger that other phones I have used. 
You have to be very accurate in going for right where the image creates an "edge" in order to "catch" it.

**Comment by NeoTheThird** [comment]
Weird... On other devices (I tried FP2, Nexus 5, M10 HD) you can pretty much swipe whereever you want.

**Comment by ChloeWolfieGirl** [comment]
As long as youre not touching any of the 3 bottom buttons you shouldn't be havong any issues.

 Have we decided if the home button is going to be used? The pro5 has a hardware button and its used to go to the scopes.

**Comment by NeoTheThird** [comment]
Just speculating here, but it might even be possible to make use of the back buttons inside apps that use qml page-stacks for example. The question is, if we want that.

**Comment by ChloeWolfieGirl** [comment]
It'd be helpful for those who have bigger phones and smaller hands.

As long as apps dont assume a back key is available, I think the option for a user to use a button thats already on there phone, would be good.

**Comment by mariogrip** [comment]
Fix pushed https://github.com/ubports/android_kernel_oneplus_msm8974/commit/b31867b3d14105efad7bf4e7420851f01a44966a
