### ISSUE TITLE
Consumpion of batery

### ISSUE THREAD

**Issue by CesarHerreraG** [ubports/ubports-touch#57]
I have an E4.5 with r4 and I think it consumes a lot of batery.

**Comment by APokorny** [comment]
This might not be krillin specific, I can claim the same for mako right now.

**Comment by APokorny** [comment]
Updated one of my krillins to r4 - battery level is still a straight horizontal line. 

Please add more information - activate developer mode - log into the device then let it suspend. Now look for activity - i.e. top .. /var/log/repowerd.log ... or launch a dbus-monitor for system and session dbus.

**Comment by NeoTheThird** [comment]
How much battery consumption are we talking? Does it last 6 hours? A day? How long did it usually last on Android or Stock Ubuntu Touch?

**Comment by APokorny** [comment]
Krillin with disabled wifi/bt/gps but with active cell radio in standby should last a few days.

**Comment by CesarHerreraG** [comment]
At 10:00 it was 100%. At 16:00 it was 30%
The other days at 16:00 is 70%
I did a clean install, but after several tries.

**Comment by CesarHerreraG** [comment]
https://ln.sync.com/dl/d8a1e7bd0/2wjtxsa8-57p6dcdh-4aikd2t8-2ewz8wci
https://ln.sync.com/dl/0b4b09e70/bzan358b-67ruvfb3-p5cuyrha-sh35vfae
https://ln.sync.com/dl/5d91e7d70/45vnpqgh-t8b6j5b2-t5weahhp-e4h49x24
https://ln.sync.com/dl/fe52c3160/urx9kwc6-dxxrrbjt-ge4y67r5-7kz7nygu
https://ln.sync.com/dl/54fc55d40/n3uyr56b-pe3dc9uk-thxrbij6-g5grpgf7

**Comment by CesarHerreraG** [comment]
During the night it has only lost 3% of battery. So I think this was a mistake on my part. We should close the matter. I'm very sorry about what happened. I will have to wait longer before talking about a bug.

**Comment by NeoTheThird** [comment]
Good to hear :) @APokorny are we good on closing this or do you want to keep it for Mako?

**Comment by APokorny** [comment]
I already have two leads for the mako issue that are system.img related.
