### ISSUE TITLE
Mako - Music App fails to connect to media hub

### ISSUE THREAD

**Issue by ernesst** [ubports/ubports-touch#58]
Gents, 

On the nexus 4 image the sound doesn't work, i cannot open music apps or try to play a ringtone. 
Let me know what log do you need. 

Devices : 
Nexus 4, legacy + multirom

Please confirm on other devices that the bug isn't coming from multirom. 
Please apply Mako label on this topic.

**Comment by APokorny** [comment]
Just tried that on my mako - sound works fine. I will have a second look later when the battery is full again. Maybe I can figure out some key traces to look for.

**Comment by ernesst** [comment]
Interesting, which log file should i look at ?

**Comment by APokorny** [comment]
/var/log/dmesg and or /var/log/syslog

**Comment by NeoTheThird** [comment]
<just a quick reminder> UBports does not support Multirom. What works works, what doesn't work will not necessarily be fixed.</just a quick reminder>

**Comment by ernesst** [comment]
Fully aware that 's why i've mentioned that it's with multirom and asked somebody else to test.

**Comment by ernesst** [comment]
I guess you can remove Multirom specification into the title, i've check with another nexus 4 and the problem is the same.

I've found this that may help : 
```
phablet@ubuntu-phablet:~$ less .cache/upstart/media-hub.log 
library "libstagefright_soft_h264dec.so" not found
library "libstagefright_soft_hevcdec.so" not found
library "libstagefright_soft_vpxdec.so" not found
library "libstagefright_soft_vpxdec.so" not found
library "libstagefright_soft_vpxenc.so" not found

ERROR: Caught a segmentation fault while loading plugin file:
/usr/lib/arm-linux-gnueabihf/gstreamer-1.0/libgstandroidmedia.so

Please either:
- remove it and restart.
- run with --gst-disable-segtrap --gst-disable-registry-fork and debug.
```
there is also

less .cache/upstart/application-click-com.ubuntu.music_music_2.5.1019.log

```
virtual QMediaService* AalServicePlugin::create(const QString&) "org.qt-project.qt.mediaplayer"
[TT 2017-05-28 21:57:17.565057] [service.cpp:29@instance] 
Failed to start a new media-hub player session:  org.freedesktop.DBus.Error.ServiceUnknown: The name core.ubuntu.media.Service was not provided by any .service files
Failed to create a new media player backend. Video playback will not function. 

Could not finish contructing new AalMediaPlayerService instance since m_hubPlayerSession is NULL
```

While playing with the keypad to dial, there is sound.

**Comment by ernesst** [comment]
So some update 
When i launch music app i see in /var/log/apport.log, coming again and again.
```

ERROR: apport (pid 5138) Sat Jun 10 19:05:15 2017: debug: session gdbus call: 
ERROR: apport (pid 5138) Sat Jun 10 19:05:15 2017: apport: report /var/crash/_usr_lib_arm-linux-gnueabihf_qt5_bin_qmlscene.32011.crash already exists and unseen, doing nothing to avoid disk usage DoS
ERROR: apport (pid 5377) Sat Jun 10 19:08:58 2017: called for pid 5340, signal 11, core limit 0
ERROR: apport (pid 5377) Sat Jun 10 19:08:58 2017: executable: /usr/lib/arm-linux-gnueabihf/qt5/bin/qmlscene (command line "/usr/lib/arm-linux-gnueabihf/qt5/bin/qmlscene app/music-app.qml --url= -I ./plugins")
ERROR: apport (pid 5377) Sat Jun 10 19:08:58 2017: gdbus call error: Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

ERROR: apport (pid 5377) Sat Jun 10 19:08:58 2017: debug: session gdbus call: 
ERROR: apport (pid 5377) Sat Jun 10 19:09:16 2017: wrote report /var/crash/_usr_lib_arm-linux-gnueabihf_qt5_bin_qmlscene.32011.crash
```
Between pid 5138 and 5377, i've deleted  /var/crash/_usr_lib_arm-linux-gnueabihf_qt5_bin_qmlscene.32011.crash to get the one for the last rev. 
See the file enclosed
[_usr_lib_arm-linux-gnueabihf_qt5_bin_qmlscene.32011.crash.zip](https://github.com/ubports/ubports-touch/files/1066190/_usr_lib_arm-linux-gnueabihf_qt5_bin_qmlscene.32011.crash.zip)

**Comment by APokorny** [comment]
Ok now that the stagefright plugins are in the device tarball, media-hub gets stuck somewhat later.
Media-hub intializes gst via gst_init which then launches  gst-plugin-scanner, this process is supposed to validate the available plugins. Now when the hybris plugin is handled this process gets stuck. The last trace is about about scanning for available codecs.

.. more digging ahead ..

**Comment by APokorny** [comment]
The process dies while loading libmedia_compat_layer.so this is part of hybris..

**Comment by garro95** [comment]
How can I help?

**Comment by garro95** [comment]
Any news about this?

**Comment by NeoTheThird** [comment]
This should be fixed on the latest RC and Devel, can someone confirm? https://ubports.com/blog/ubports-blog-1/post/road-to-ota-2-75

**Comment by ernesst** [comment]
On the last devel, the problem is still there.

**Comment by fmulcar** [comment]
I made a complete devel rev 143 installation and we still have no sound and no network data

**Comment by garro95** [comment]
Now working on my device on devel 15.04 r144

**Comment by ernesst** [comment]
Yesss ! Great job thanks
