### ISSUE TITLE
Can't make outgoing phone calls (Bacon)

### ISSUE THREAD

**Issue by tomoqv** [ubports/ubports-touch#61]
OPO on legacy r15

Steps:
When I make an outgoing phone call, the other phone rings. As soon as the call is picked up by the receiving end, OPO says call failed and hangs up, but the call still appears ongoing on the receiving phone (albeit with no audio). After that, OPO reattempts the call, and this time receiving phone doesn't ring or show incoming call. It is also not possible to terminate the call on the OPO.

Expected:
Pretty obvious, but that OPO will connect the external call and keep it. And that it won't attempt to retry phone calls on its own.

Incoming calls to the OPO seems to work, though. I have only tested this calling from my other phone, but fingers crossed.

Due to this issue https://github.com/ubports/ubports-touch/issues/13 I am not able to easily extract the desired log files.

**Comment by NeoTheThird** [comment]
Might be related to #12.

**Comment by tomoqv** [comment]
I just switched SIM cards in my two phones. OPO still can't make outgoing phone calls. Same problem regardless of SIM Tele2 or Comviq (maybe not surprising as Comviq is part of Tele2).

**Comment by mariogrip** [comment]
Should be fixed in: https://github.com/ubports/android_device_oneplus_bacon-1/commit/a10bb129a3194579e0c702fdd6f2c77214ea551b 

Please give feedback if you still have this issue.

**Comment by tomoqv** [comment]
Did this fix make it into r20? In that case, the issue still remains.

**Comment by mariogrip** [comment]
@tomoqv It does not seem to have been included in the latest update, I will trigger a new build now.

**Comment by tomoqv** [comment]
@mariogrip Just waiting for the new build to filter through and become available on my device...
