### ISSUE TITLE
Mako - Calls and network mobile information does not work

### ISSUE THREAD

**Issue by fmulcar** [ubports/ubports-touch#63]
Calls and network mobile information does not work.

**Comment by NeoTheThird** [comment]
Thank you for reporting this. For future bug reports, please sum up the most important information in the title of the issue and provide further information (Logs, steps to reproduce, etc.) on the bug in the description if necessary. (No offense.) It's ok for a clear issue like this one, but debug information is vital for most bug reports. If you're interested, you can [read our guide on writing a good bug report](https://wiki.ubports.com/wiki/Writing-a-Good-Bug-Report). Thank you :)

**Comment by garro95** [comment]
Confirm working on devel 15.04 r144
