### ISSUE TITLE
Nexus 4 legay rev7

### ISSUE THREAD

**Issue by fmulcar** [ubports/ubports-touch#71]
Boys I have my nexus 4 without being able to answer to the calls, because the sound does not work.
In the work I am without connection because the mobile network does not work.
I am with the last update and it follows the same problem.
That I can do?
To install the version of canonical and to wait to the stable version of ubports?
Thank you for this great work.

**Comment by NeoTheThird** [comment]
Thank you for reporting this. For future bug reports, please sum up the most important information in the title of the issue and provide further information (Logs, steps to reproduce, etc.) on the bug in the description if necessary. (No offense.) It's ok for a clear issue like this one, but debug information is vital for most bug reports. If you're interested, [you can read our guide on writing a good bug report](https://wiki.ubports.com/wiki/Writing-a-Good-Bug-Report). Thank you :)

**Comment by NeoTheThird** [comment]
Didn't you already report this at #63?

**Comment by NeoTheThird** [comment]
"To install the version of canonical and to wait to the stable version of ubports?
Thank you for this great work."

Yes, if you are dependent on your device, you could go back to the canonical image for now and return to UBports as soon as we fixed this.
