### ISSUE TITLE
Show changelogs for OTA updates

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/ubports-touch#72]
From [Launchpad](https://bugs.launchpad.net/canonical-devices-system-image/+bug/1592388):

What happens:
Get notification about system update, but there's no information about what the update contains

What should happen:
The update should contain human readable information about the update

In reality, the following must be implemented to allow this to happen:

* Enable developers to add pieces to changelogs as they happen, or pull a commit log automatically
* Add a field to the image manifest on the system-image-server OR create a companion service for changelogs OR pull changelogs from GitHub
* Add parsing of this data to system-image-client
* Add a place to display this information in ubuntu-system-settings

**Comment by Flohack74** [comment]
I think we can use the Release feature of Github. It will just be necessary to commit smth into the Repo (maybe the raw version of the changelog), then tag this with the OTA-x tag, and then create a release for that. This allows us to review/pretty-print the changelog as necessary.

We can add a file to the overlay which can then be printed somewhere in the update screen and maybe also in the "About" section of the system info.

Better ideas please! :)

**Comment by NeoTheThird** [comment]
It would be really cool to show it in the Update screen in the settings, so that you can see it before you install the update. Similar to the way Changelogs for Apps from the Click store are displayed.

**Comment by WLBI** [comment]
Before on my E4.5 I used the rc.proposed and there on the "updates" screen, just tap on the grey version number below and the text gets extended and you was able to see, what changed in that update.
But sure, that was available after you installed the update.

**Comment by mariogrip** [comment]
Fixed with https://github.com/ubports/system-settings/pull/17/commits/25152ba4f8de8820e254f41b5281faed51d673e3
