### ISSUE TITLE
About - Ubports links

### ISSUE THREAD

**Issue by ernesst** [ubports/ubports-touch#75]
As an idea to redirect users efficiently to Ubport information : 
What about integrating into the OS a webapp redirecting to a Ubport page where all the shortcut would be listed : 
- main website,
- wiki
- bug report
- patreon
- Telegram link
- etc....

The advantage of an UBport page, it would be independent of the phone / image / update

All the users will have easily access to the community.

**Comment by NeoTheThird** [comment]
I wanted to get more done, but my unstable internet of the last few days had other plans. Anyways, here's what I've got: https://github.com/ubports/ubports-app
