### ISSUE TITLE
Add indicator to activate the Flashlight

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-touch#79]
At the moment, using the camera flash is only possible through [uTorch](https://uappexplorer.com/app/com.ubuntu.developer.majster-pl.utorch). Since it's a very useful feature, it would make sense to integrate it into the system. This could be done by preinstalling uTorch (or an App with the same functionality) or adding a flashlight indicator that's accessible from the top edge.

**Comment by NeoTheThird** [comment]
#78 should probably be fixed first to avoid duplicate effort.

**Comment by NeoTheThird** [comment]
Props to @rubencarneiro for fixing it for the FP: https://github.com/ubports/android_device_fairphone_fp2/commit/04232913d3673fec205dabb1442b997f1cec13a8

**Comment by nfsprodriver** [comment]
https://github.com/nfsprodriver/ut-indicator-torch This is an attempt tested on hammerhead/devel (because it accesses sys leds directly). It's meant to be chaned to CameraAPI, I think. The work is based on bhdouglass' indicator-weather - project. [https://github.com/bhdouglass/ut-indicator-weather](url)

**Comment by rubencarneiro** [comment]
https://github.com/ubports/device-files/pull/23

**Comment by mariogrip** [comment]
Where should this be placed in "battery" is an option, what do you think?

**Comment by NeoTheThird** [comment]
@mariogrip That would be an option. It does make sense to not add too many separate indicators to improve ease of navigation.

**Comment by ChloeWolfieGirl** [comment]
That would work very well, I thinknitd be good to see if theres any other smaller indicators that could be used.

Rotation is by itself, perhaps it could be merged with battery as well?

What about keyboard and location, do they need much space or can they be merged with something?

**Comment by NeoTheThird** [comment]
@ChloeWolfieGirl I think they should both stay seperate, since the purpose of the indicator is also to provide the indicator icon (suprise) when a certain condition is met, so you can see if there's an app accessing your location or if you locked rotation. The torch indicator, on the other hand doesn't necessarily need an indicator, but only a menu item, since you're not supposed to keep on the torch for too long anyways.

**Comment by nfsprodriver** [comment]
Here is a Torch indicator: https://open.uappexplorer.com/app/indicator-torch.nfsprodriver Please read the description.
