### ISSUE TITLE
UBports builds do not load important environment variables from /etc/ubuntu-session.d/

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubports-touch#80]
As users reported in #17 there are issues with the recognition of a device regarding it´s graphical features and physical size.

Canonical wanted to address the differences between devices with the idea of loading a device-dependent configuration from /etc/ubuntu-session.d/ - there a .conf file with the device name (mako.conf, manta.conf etc) would be loaded first if it exists, and then it would load android.conf as a generic one.

Both doesn´t seem to happen on our builds. This leads to a wrong UA string construction in the webbrowser, but may also have other impacts.

On the long run we should find another way to do this. For example for convergence it is important to know the current capabilities (in mobile mode or docked), and not follow hardcoded values.

**Comment by Flohack74** [comment]
Taking @mariogrip into this one since I can´t debug it on myself it seems => plz ping me on Telegram if you have approx 20mins of time.

**Comment by mariogrip** [comment]
UBports devices do indeed use this, example for bacon. For some reason it does not have any effect on the browser UA https://github.com/ubports/android_device_oneplus_bacon-1/blob/ubp-5.1/ubuntu/android.conf

**Comment by Flohack74** [comment]
Just putting the file in the image might not be enough...
