### ISSUE TITLE
When open Emergency call with the SIM locked, there is no way to go back

### ISSUE THREAD

**Issue by mymike00** [ubports/ubports-touch#82]
When I restart the phone, it asks me for the pin of my SIM. under the numpad there is a button `Emergency call` and when I click on it, it takes me here:
![emercency call](https://cloud.githubusercontent.com/assets/28359593/26760405/46bb94f2-4917-11e7-8bc5-40234281ab02.png)
It's fullscreen and there is no `back` button because there is the one to unlock the SIM.
The phone is already locked and I can't either swipe from right/left and close the app...
That screen appears also if I don't unlock the SIM and I continue to use the phone with the  SIM locked and when I'm on the lockscreen (where it asks for the phone passphrase/passcode) and I click on another `Emergency call` button...
There is no problem if I click on that button when I insert before the pin of my SIM and I unlocked it

**Comment by Flohack74** [comment]
Confirmed on BQ E5... so its an old design flaw :)

**Comment by Flohack74** [comment]
Workaround: Swipe into the dash on the left edge, click on the orange Ubuntu icon. Then you can change to the launcher menu. From there, unload the phone app.

Unlock the SIM card(s) by pulling down the top menu and press on Unlock.

**Comment by mymike00** [comment]
> Workaround: Swipe into the dash on the left edge, click on the orange Ubuntu icon. Then you can change to the launcher menu. From there, unload the phone app.
That doesn't work for me, I have to lock the screen and then switch it on

**Comment by mariogrip** [comment]
Fixed https://github.com/ubports/dialer-app/commit/bc4ec97504a27e029ece4aff556c233ccd3b2c71
