### ISSUE TITLE
Last update date is wrong

### ISSUE THREAD

**Issue by ebeton-ro** [ubports/ubports-touch#83]
I just updated my Nexus 5 to r26 I had this device in Romanian language, and I think is a conversion problem (not sure just guessing here) but the update date is wrong as you can see for yourself it should be 05.07.2017 not 24.06.1973 .

![screenshot20170605_003123289](https://cloud.githubusercontent.com/assets/9527462/26765636/a1e4dac0-4988-11e7-9a25-7854aeddc365.png)

**Comment by peat-psuwit** [comment]
This is #5 but in recovery. This also happens on FP2, or, actually, almost every Qualcomm devices.

**Comment by ebeton-ro** [comment]
So it's not even language related... or device...It's RTC related.

**Comment by ebeton-ro** [comment]
As a notice in r27 that I just installed the date is the same so it seems that @peat-psuwit  is right about the RTC being the problem and not the language conversion.

**Comment by tomoqv** [comment]
I am getting 1972-11-24 on my OPO.

**Comment by bastos77** [comment]
I am getting 11.01.1970 on my FP2

**Comment by NeoTheThird** [comment]
Did this happen again? Let's close it for now. Also, it might be a little pointless to retrospectively change the date... Let's observe if this happens again in the future.

**Comment by ebeton-ro** [comment]
@NeoTheThird still present on my Nexus 5 device with R197 so i do not know if it is ok to close it.

**Comment by Flohack74** [comment]
Maybe it is a consequence of https://github.com/ubports/ubuntu-touch/issues/5 because when the update date is saved the system clock is not set correctly on boot.
