### ISSUE TITLE
Hammerhead - Legacy update 28 -> 30 failed

### ISSUE THREAD

**Issue by ernesst** [ubports/ubports-touch#87]
Gents,

There is a problem with last update, see picture:
![image](https://user-images.githubusercontent.com/11337464/26859503-cbea59fa-4afd-11e7-83e7-9c61d85c0053.png)

**Comment by ernesst** [comment]
After 2 reboot the update went successful.

**Comment by bastos77** [comment]
Too much devices trying to update :-)))))
