### ISSUE TITLE
BQ Aquaris M10 FHD - browser no longer supported by ebay

### ISSUE THREAD

**Issue by Cacadoo** [ubports/ubports-touch#88]
This issue already existed in the Canonical era. It was fixed in OTA 15. 
Now it seems, the issue is back again.

Here to see on launchpad: https://bugs.launchpad.net/webapps-core/+bug/1575780

![screenshot20170608_090846616](https://user-images.githubusercontent.com/18295202/26916353-5d6adf30-4c2a-11e7-96f3-3a5a455e9b5b.png)

**Comment by NeoTheThird** [comment]
Funny enough it works on the M10 HD (cooler).

**Comment by Flohack74** [comment]
They targeted it way too far (zesty): webbrowser-app (0.23+17.04.20170125.1-0ubuntu1) zesty; urgency=medium - see LP bug :)

**Comment by NeoTheThird** [comment]
As a workaround you can visit the desktop site from the link in the footer.

**Comment by mariogrip** [comment]
Fixed https://github.com/ubports/webbrowser-app/commit/ee2b4f574ec328f0cd7da933b798116997199366
