### ISSUE TITLE
Phone and messages are installed on tablet

### ISSUE THREAD

**Issue by thedimmu** [ubports/ubports-touch#93]
The phone and message app are installed by default on the tablet, they should only be on phones.

**Comment by Flohack74** [comment]
Well theoretically I agree, but there are tablets with SIM cards :P

**Comment by doniks** [comment]
So it should probably say: Install them if the capability is there. I think it was like this on the two nexus 7 images back in the day: deb has sim and phone apps. flo had neither.

**Comment by mariogrip** [comment]
Fixed, http://cdimage.ubports.com/devices/device_cooler.tar.xz http://cdimage.ubports.com/devices/device_frieza.tar.xz
