### ISSUE TITLE
Replace hammerhead battery hack (#6) with actual solution

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports-touch#94]
The battery issue on Nexus 5 (#6) is only fixed with a hack. This should be replaced with an actual solution: ubports/device-files/commit/367bcfa62f27508845300fd1d69842d87eff5d67

**Comment by rubencarneiro** [comment]
Not fixed, when battery reaches below 50% indicator reports at 100%

**Comment by Osndok** [comment]
I don't know **exactly** how it is related, but (while investigating [sensor related cpu usage](https://forums.ubports.com/topic/358/nexus-5-hammerhead-battery-boost-disable-auto-rotate-reboot-for-slower-drain))  I discovered that if you:

1. enable rotation lock (or disable auto rotate)
2. reboot the phone, and then
3. allow the device to fully charge

...this seems to clear up the battery issues **I was having** (battery stuck at 50%, high drain, etc).

**Comment by NeoTheThird** [comment]
Since this is not that pressing, let's postpone it to OTA-3.
