### ISSUE TITLE
Start is very long

### ISSUE THREAD

**Issue by laurentGarry** [ubports/ubports-touch#99]
The startup lasts more than 3 minutes

**Comment by Flohack74** [comment]
Please be more specific, which device & which channel you are on?

**Comment by laurentGarry** [comment]
Is it "Ubuntu 15.4 (R11)"
I had a problem with the UT start Ubports before the M10 tablet started up very fast

**Comment by Flohack74** [comment]
@NeoTheThird what do we  know about start times of the tablets right now? Whats your experience?

**Comment by samtygier** [comment]
Duplicate of #53

**Comment by NeoTheThird** [comment]
This has already been reported on #53.
